package org.cloud.model;

/**
 * LvbtodrId generated by MyEclipse Persistence Tools
 */

public class LvbtodrId implements java.io.Serializable {

	// Fields

	private String tntcod;

	private String odrmgtnum;

	// Constructors

	/** default constructor */
	public LvbtodrId() {
	}

	/** full constructor */
	public LvbtodrId(String tntcod, String odrmgtnum) {
		this.tntcod = tntcod;
		this.odrmgtnum = odrmgtnum;
	}

	// Property accessors

	public String getTntcod() {
		return this.tntcod;
	}

	public void setTntcod(String tntcod) {
		this.tntcod = tntcod;
	}

	public String getOdrmgtnum() {
		return this.odrmgtnum;
	}

	public void setOdrmgtnum(String odrmgtnum) {
		this.odrmgtnum = odrmgtnum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LvbtodrId))
			return false;
		LvbtodrId castOther = (LvbtodrId) other;

		return ((this.getTntcod() == castOther.getTntcod()) || (this
				.getTntcod() != null
				&& castOther.getTntcod() != null && this.getTntcod().equals(
				castOther.getTntcod())))
				&& ((this.getOdrmgtnum() == castOther.getOdrmgtnum()) || (this
						.getOdrmgtnum() != null
						&& castOther.getOdrmgtnum() != null && this
						.getOdrmgtnum().equals(castOther.getOdrmgtnum())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTntcod() == null ? 0 : this.getTntcod().hashCode());
		result = 37 * result
				+ (getOdrmgtnum() == null ? 0 : this.getOdrmgtnum().hashCode());
		return result;
	}

}