package org.cloud.model;

/**
 * LvbtodrdtmId generated by MyEclipse Persistence Tools
 */

public class LvbtodrdtmId implements java.io.Serializable {

	// Fields

	private String tntcod;

	private String odrmgtnum;

	private String odrdhmmgtnum;

	// Constructors

	/** default constructor */
	public LvbtodrdtmId() {
	}

	/** full constructor */
	public LvbtodrdtmId(String tntcod, String odrmgtnum, String odrdhmmgtnum) {
		this.tntcod = tntcod;
		this.odrmgtnum = odrmgtnum;
		this.odrdhmmgtnum = odrdhmmgtnum;
	}

	// Property accessors

	public String getTntcod() {
		return this.tntcod;
	}

	public void setTntcod(String tntcod) {
		this.tntcod = tntcod;
	}

	public String getOdrmgtnum() {
		return this.odrmgtnum;
	}

	public void setOdrmgtnum(String odrmgtnum) {
		this.odrmgtnum = odrmgtnum;
	}

	public String getOdrdhmmgtnum() {
		return this.odrdhmmgtnum;
	}

	public void setOdrdhmmgtnum(String odrdhmmgtnum) {
		this.odrdhmmgtnum = odrdhmmgtnum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LvbtodrdtmId))
			return false;
		LvbtodrdtmId castOther = (LvbtodrdtmId) other;

		return ((this.getTntcod() == castOther.getTntcod()) || (this
				.getTntcod() != null
				&& castOther.getTntcod() != null && this.getTntcod().equals(
				castOther.getTntcod())))
				&& ((this.getOdrmgtnum() == castOther.getOdrmgtnum()) || (this
						.getOdrmgtnum() != null
						&& castOther.getOdrmgtnum() != null && this
						.getOdrmgtnum().equals(castOther.getOdrmgtnum())))
				&& ((this.getOdrdhmmgtnum() == castOther.getOdrdhmmgtnum()) || (this
						.getOdrdhmmgtnum() != null
						&& castOther.getOdrdhmmgtnum() != null && this
						.getOdrdhmmgtnum().equals(castOther.getOdrdhmmgtnum())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTntcod() == null ? 0 : this.getTntcod().hashCode());
		result = 37 * result
				+ (getOdrmgtnum() == null ? 0 : this.getOdrmgtnum().hashCode());
		result = 37
				* result
				+ (getOdrdhmmgtnum() == null ? 0 : this.getOdrdhmmgtnum()
						.hashCode());
		return result;
	}

}