package org.cloud.model;

import java.util.Date;

/**
 * Lvbtodrdtm generated by MyEclipse Persistence Tools
 */

public class Lvbtodrdtm implements java.io.Serializable {

	// Fields

	private LvbtodrdtmId id;

	private String dhmkbn;

	private String estreskbn;

	private Date ymd;

	private String tim;

	private String statim;

	private String endtim;

	private String dgntimcod;

	private String insymdhms;

	private String insnam;

	private String inskbn;

	private String insmethodkbn;

	private Long updeac;

	private String updymdhms;

	private String updnam;

	private String updkbn;

	private String updmethodkbn;

	// Constructors

	/** default constructor */
	public Lvbtodrdtm() {
	}

	/** minimal constructor */
	public Lvbtodrdtm(LvbtodrdtmId id) {
		this.id = id;
	}

	/** full constructor */
	public Lvbtodrdtm(LvbtodrdtmId id, String dhmkbn, String estreskbn,
			Date ymd, String tim, String statim, String endtim,
			String dgntimcod, String insymdhms, String insnam, String inskbn,
			String insmethodkbn, Long updeac, String updymdhms, String updnam,
			String updkbn, String updmethodkbn) {
		this.id = id;
		this.dhmkbn = dhmkbn;
		this.estreskbn = estreskbn;
		this.ymd = ymd;
		this.tim = tim;
		this.statim = statim;
		this.endtim = endtim;
		this.dgntimcod = dgntimcod;
		this.insymdhms = insymdhms;
		this.insnam = insnam;
		this.inskbn = inskbn;
		this.insmethodkbn = insmethodkbn;
		this.updeac = updeac;
		this.updymdhms = updymdhms;
		this.updnam = updnam;
		this.updkbn = updkbn;
		this.updmethodkbn = updmethodkbn;
	}

	// Property accessors

	public LvbtodrdtmId getId() {
		return this.id;
	}

	public void setId(LvbtodrdtmId id) {
		this.id = id;
	}

	public String getDhmkbn() {
		return this.dhmkbn;
	}

	public void setDhmkbn(String dhmkbn) {
		this.dhmkbn = dhmkbn;
	}

	public String getEstreskbn() {
		return this.estreskbn;
	}

	public void setEstreskbn(String estreskbn) {
		this.estreskbn = estreskbn;
	}

	public Date getYmd() {
		return this.ymd;
	}

	public void setYmd(Date ymd) {
		this.ymd = ymd;
	}

	public String getTim() {
		return this.tim;
	}

	public void setTim(String tim) {
		this.tim = tim;
	}

	public String getStatim() {
		return this.statim;
	}

	public void setStatim(String statim) {
		this.statim = statim;
	}

	public String getEndtim() {
		return this.endtim;
	}

	public void setEndtim(String endtim) {
		this.endtim = endtim;
	}

	public String getDgntimcod() {
		return this.dgntimcod;
	}

	public void setDgntimcod(String dgntimcod) {
		this.dgntimcod = dgntimcod;
	}

	public String getInsymdhms() {
		return this.insymdhms;
	}

	public void setInsymdhms(String insymdhms) {
		this.insymdhms = insymdhms;
	}

	public String getInsnam() {
		return this.insnam;
	}

	public void setInsnam(String insnam) {
		this.insnam = insnam;
	}

	public String getInskbn() {
		return this.inskbn;
	}

	public void setInskbn(String inskbn) {
		this.inskbn = inskbn;
	}

	public String getInsmethodkbn() {
		return this.insmethodkbn;
	}

	public void setInsmethodkbn(String insmethodkbn) {
		this.insmethodkbn = insmethodkbn;
	}

	public Long getUpdeac() {
		return this.updeac;
	}

	public void setUpdeac(Long updeac) {
		this.updeac = updeac;
	}

	public String getUpdymdhms() {
		return this.updymdhms;
	}

	public void setUpdymdhms(String updymdhms) {
		this.updymdhms = updymdhms;
	}

	public String getUpdnam() {
		return this.updnam;
	}

	public void setUpdnam(String updnam) {
		this.updnam = updnam;
	}

	public String getUpdkbn() {
		return this.updkbn;
	}

	public void setUpdkbn(String updkbn) {
		this.updkbn = updkbn;
	}

	public String getUpdmethodkbn() {
		return this.updmethodkbn;
	}

	public void setUpdmethodkbn(String updmethodkbn) {
		this.updmethodkbn = updmethodkbn;
	}

}