package org.cloud.model;

import java.util.Date;

/**
 * LmmmitmId generated by MyEclipse Persistence Tools
 */

public class LmmmitmId implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String tntcod; 

	private String itmcod;

	private Date appstaymdhms;

	// Constructors

	/** default constructor */
	public LmmmitmId() {
	}

	/** full constructor */
	public LmmmitmId(String tntcod, String itmcod, Date appstaymdhms) {
		this.tntcod = tntcod;
		this.itmcod = itmcod;
		this.appstaymdhms = appstaymdhms;
	}

	// Property accessors

	public String getTntcod() {
		return this.tntcod;
	}

	public void setTntcod(String tntcod) {
		this.tntcod = tntcod;
	}

	public String getItmcod() {
		return this.itmcod;
	}

	public void setItmcod(String itmcod) {
		this.itmcod = itmcod;
	}

	public Date getAppstaymdhms() {
		return appstaymdhms;
	}

	public void setAppstaymdhms(Date appstaymdhms) {
		this.appstaymdhms = (Date)appstaymdhms;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LmmmitmId))
			return false;
		LmmmitmId castOther = (LmmmitmId) other;

		return ((this.getTntcod() == castOther.getTntcod()) || (this
				.getTntcod() != null
				&& castOther.getTntcod() != null && this.getTntcod().equals(
				castOther.getTntcod())))
				&& ((this.getItmcod() == castOther.getItmcod()) || (this
						.getItmcod() != null
						&& castOther.getItmcod() != null && this.getItmcod()
						.equals(castOther.getItmcod())))
				&& ((this.getAppstaymdhms() == castOther.getAppstaymdhms()) || (this
						.getAppstaymdhms() != null
						&& castOther.getAppstaymdhms() != null && this
						.getAppstaymdhms().equals(castOther.getAppstaymdhms())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTntcod() == null ? 0 : this.getTntcod().hashCode());
		result = 37 * result
				+ (getItmcod() == null ? 0 : this.getItmcod().hashCode());
		result = 37
				* result
				+ (getAppstaymdhms() == null ? 0 : this.getAppstaymdhms()
						.hashCode());
		return result;
	}



}