package org.cloud.model;

import java.util.Date;

/**
 * Lmmmorgitm generated by MyEclipse Persistence Tools
 */

@SuppressWarnings("serial")
public class Lmmmorgitm implements java.io.Serializable {

	// Fields
	private String tntcod;

	private String orgcod;

	private String orgitmcod;

	private Date appstaymdhms;
	public String getTntcod() {
		return tntcod;
	}

	public void setTntcod(String tntcod) {
		this.tntcod = tntcod;
	}

	public String getOrgcod() {
		return orgcod;
	}

	public void setOrgcod(String orgcod) {
		this.orgcod = orgcod;
	}

	public String getOrgitmcod() {
		return orgitmcod;
	}

	public void setOrgitmcod(String orgitmcod) {
		this.orgitmcod = orgitmcod;
	}

	public Date getAppstaymdhms() {
		return appstaymdhms;
	}

	public void setAppstaymdhms(Date appstaymdhms) {
		this.appstaymdhms = appstaymdhms;
	}

	private LmmmorgitmId id;

	private String aboflg;

	private String orgitmnam;

	private String itmcod;

	private String apporgcod;

	private Date appendymdhms;

	private Date insymdhms;

	private String insnam;

	private String inskbn;

	private String insmethodkbn;

	private Long updeac;

	private Date updymdhms;

	private String updnam;

	private String updkbn;

	private String updmethodkbn;

	// Constructors

	/** default constructor */
	public Lmmmorgitm() {
	}

	/** minimal constructor */
	public Lmmmorgitm(LmmmorgitmId id) {
		this.id = id;
	}

	/** full constructor */
	public Lmmmorgitm(LmmmorgitmId id, String aboflg, String orgitmnam,
			String itmcod, String apporgcod, Date appendymdhms,
			Date insymdhms, String insnam, String inskbn,
			String insmethodkbn, Long updeac, Date updymdhms, String updnam,
			String updkbn, String updmethodkbn) {
		this.id = id;
		this.aboflg = aboflg;
		this.orgitmnam = orgitmnam;
		this.itmcod = itmcod;
		this.apporgcod = apporgcod;
		this.appendymdhms = appendymdhms;
		this.insymdhms = insymdhms;
		this.insnam = insnam;
		this.inskbn = inskbn;
		this.insmethodkbn = insmethodkbn;
		this.updeac = updeac;
		this.updymdhms = updymdhms;
		this.updnam = updnam;
		this.updkbn = updkbn;
		this.updmethodkbn = updmethodkbn;
	}

	// Property accessors

	public LmmmorgitmId getId() {
		return this.id;
	}

	public void setId(LmmmorgitmId id) {
		this.id = id;
	}

	public String getAboflg() {
		return this.aboflg;
	}

	public void setAboflg(String aboflg) {
		this.aboflg = aboflg;
	}

	public String getOrgitmnam() {
		return this.orgitmnam;
	}

	public void setOrgitmnam(String orgitmnam) {
		this.orgitmnam = orgitmnam;
	}

	public String getItmcod() {
		return this.itmcod;
	}

	public void setItmcod(String itmcod) {
		this.itmcod = itmcod;
	}

	public String getApporgcod() {
		return this.apporgcod;
	}

	public void setApporgcod(String apporgcod) {
		this.apporgcod = apporgcod;
	}

	public Date getAppendymdhms() {
		return this.appendymdhms;
	}

	public void setAppendymdhms(Date appendymdhms) {
		this.appendymdhms = appendymdhms;
	}

	public Date getInsymdhms() {
		return this.insymdhms;
	}

	public void setInsymdhms(Date insymdhms) {
		this.insymdhms = insymdhms;
	}

	public String getInsnam() {
		return this.insnam;
	}

	public void setInsnam(String insnam) {
		this.insnam = insnam;
	}

	public String getInskbn() {
		return this.inskbn;
	}

	public void setInskbn(String inskbn) {
		this.inskbn = inskbn;
	}

	public String getInsmethodkbn() {
		return this.insmethodkbn;
	}

	public void setInsmethodkbn(String insmethodkbn) {
		this.insmethodkbn = insmethodkbn;
	}

	public Long getUpdeac() {
		return this.updeac;
	}

	public void setUpdeac(Long updeac) {
		this.updeac = updeac;
	}

	public Date getUpdymdhms() {
		return this.updymdhms;
	}

	public void setUpdymdhms(Date updymdhms) {
		this.updymdhms = updymdhms;
	}

	public String getUpdnam() {
		return this.updnam;
	}

	public void setUpdnam(String updnam) {
		this.updnam = updnam;
	}

	public String getUpdkbn() {
		return this.updkbn;
	}

	public void setUpdkbn(String updkbn) {
		this.updkbn = updkbn;
	}

	public String getUpdmethodkbn() {
		return this.updmethodkbn;
	}

	public void setUpdmethodkbn(String updmethodkbn) {
		this.updmethodkbn = updmethodkbn;
	}

}