package org.cloud.model;

/**
 * Lmmmco generated by MyEclipse Persistence Tools
 */

@SuppressWarnings("serial")
public class Lmmmco implements java.io.Serializable {

	// Fields

	private String coalpha3;

	private String coalpha2;

	private String conum;

	private String conam;

	// Constructors

	/** default constructor */
	public Lmmmco() {
	}

	/** full constructor */
	public Lmmmco(String coalpha2, String conum, String conam) {
		this.coalpha2 = coalpha2;
		this.conum = conum;
		this.conam = conam;
	}

	// Property accessors

	public String getCoalpha3() {
		return this.coalpha3;
	}

	public void setCoalpha3(String coalpha3) {
		this.coalpha3 = coalpha3;
	}

	public String getCoalpha2() {
		return this.coalpha2;
	}

	public void setCoalpha2(String coalpha2) {
		this.coalpha2 = coalpha2;
	}

	public String getConum() {
		return this.conum;
	}

	public void setConum(String conum) {
		this.conum = conum;
	}

	public String getConam() {
		return this.conam;
	}

	public void setConam(String conam) {
		this.conam = conam;
	}

}