package org.cloud.model;

/**
 * LmmmplcId generated by MyEclipse Persistence Tools
 */

public class LmmmplcId implements java.io.Serializable {

	private static final long serialVersionUID = -8280901175469987750L;

	private String tntcod;

	private String plccod;

	// Constructors

	/** default constructor */
	public LmmmplcId() {
	}

	/** full constructor */
	public LmmmplcId(String tntcod, String plccod) {
		this.tntcod = tntcod;
		this.plccod = plccod;
	}

	// Property accessors

	public String getTntcod() {
		return this.tntcod;
	}

	public void setTntcod(String tntcod) {
		this.tntcod = tntcod;
	}

	public String getPlccod() {
		return this.plccod;
	}

	public void setPlccod(String plccod) {
		this.plccod = plccod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LmmmplcId))
			return false;
		LmmmplcId castOther = (LmmmplcId) other;

		return ((this.getTntcod() == castOther.getTntcod()) || (this
				.getTntcod() != null
				&& castOther.getTntcod() != null && this.getTntcod().equals(
				castOther.getTntcod())))
				&& ((this.getPlccod() == castOther.getPlccod()) || (this
						.getPlccod() != null
						&& castOther.getPlccod() != null && this.getPlccod()
						.equals(castOther.getPlccod())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTntcod() == null ? 0 : this.getTntcod().hashCode());
		result = 37 * result
				+ (getPlccod() == null ? 0 : this.getPlccod().hashCode());
		return result;
	}

}