package org.cloud.model;

import java.util.Date;

/**
 * Lvbtodritm generated by MyEclipse Persistence Tools
 */

public class Lvbtodritm implements java.io.Serializable {

	// Fields

	private LvbtodritmId id;

	private String dtlnum;

	private String itmcod;

	private String vitmcod;

	private String itmnam;

	private Long nbrcnt;

	private String nbrunicod;

	private Long scdnbrcnt;

	private String scdnbrunicod;

	private Long delcmpcnt;

	private String delcmpcntcod;

	private String frekndclacod;

	private String comopecod;

	private String cnttmptypcod;

	private String cnttmpunicod;

	private String cnttmpval;

	private String itmtmptypcod;

	private String itmtmpunicod;

	private String itmtmpval;

	private String batstanum;

	private String batendnum;

	private String staprdnum;

	private String endprdnum;

	private String staitmsrlnum;

	private String enditmsrlnum;

	private String stapacnum;

	private String endpacnum;

	private String trsmrkitmnam;

	private String puritmnam;

	private Long inseac;

	private String rcvmgtnum;

	private String stggdskbn;

	private String indsipnum;

	private String indodrnum;

	private String inddisprowrkcod;

	private String odrprokbncod;

	private String indfrtshpnam;

	private String indfrtshpnamcod;

	private String frtshpmgtnum;

	private String frtshpchacod;

	private String indsndshpnamcod;

	private String indsndshpnam;

	private String rcvitmnam;

	private String rcvartnum;

	private String rcvartnam;

	private String endusrnam;

	private String shptrsgdsnum;

	private String trsinvbrcnum;

	private String trsmrkitmcod;

	private String itmnam1;

	private String itmnam2;

	private String itmnam3;

	private String itmnam4;

	private String mopcod;

	private String mopnam1;

	private String mopnam2;

	private String indcapunicod;

	private String indwgtunicod;

	private String indcntunicod;

	private String sizunicod;

	private Double cnvwgtcnt;

	private String cnvunicod;

	private Double dpswgtcnt;

	private Double dpscapcnt;

	private String dpsprcunicod;

	private String dpsunimnycnt;

	private Double lodreprcvcnt;

	private String frefirinspsccod;

	private Double trspaccapreqcnt;

	private Double trspaccaprepcnt;

	private String lughndtrmnam1;

	private String lughndtrmnam2;

	private String dtlrmknam1;

	private String dtlrmknam2;

	private String dtlrmknam3;

	private String dtlrmknam4;

	private Date frepstymd;

	private String frepsthms;

	private String pstpntcod;

	private String pstpntnam;

	private String stcnum;

	private String stcdvycod;

	private String boxnum;

	private String rcvtmpsrgplccod;

	private String rcvtmpdcnplccod;

	private String rcvitmclscod;

	private String itmclscod;

	private String rcvbssspcnam;

	private String rcvaddspcnam;

	private String itmadrnam;

	private String stdcod;

	private Date mfcreqymd;

	private Date mfcrephms;

	private String lcspltnum;

	private String jancod;

	private String itfcod;

	private String lotnum;

	private String lotreqnum;

	private String lotrepnum;

	private Date mfcymd;

	private String mfchms;

	private String homenam;

	private String mfcftrnum;

	private Date bstbfrymd;

	private String bstbfrhms;

	private Date expymd;

	private String exphms;

	private String gdsstgfil;

	private String qltdeftypcod;

	private String qltkbn;

	private String setgdsadrnam;

	private String indrcvnum;

	private String lotregpsccod;

	private String inoutfretypcod;

	private Date reqbstbfrymd;

	private String reqbstbfrhms;

	private Date reqexpymd;

	private String reqexphms;

	private Date repbstbfrymd;

	private String repbstbfrhms;

	private Date repexpymd;

	private String repexphms;

	private String stkoutcod;

	private String unilodcod;

	private String unilodreqcnt;

	private String unilodrepcnt;

	private Long unilodlodcnt;

	private Long reqnumcnt;

	private Long repnumcnt;

	private Double purnumcnt;

	private String oneunicod;

	private Long oneinscnt;

	private Long onereqcnt;

	private Long onerepcnt;

	private Double cnvcofcnt;

	private String wrpcnt;

	private String wrpnumnum;

	private String ctnamtunicod;

	private Double reqcnt;

	private Double repcnt;

	private Double wrpinscnt;

	private Double itmlngsizcnt;

	private Double itmbldsizcnt;

	private Double itmhgtsizcnt;

	private String grdnam;

	private Double slsuniprcspamn;

	private Double bscunisvamn;

	private String srgtmptypcod;

	private String grdcod;

	private String clrcod;

	private String clrnam;

	private String sizcod;

	private String inseamcod;

	private Double itmwgtcnt;

	private Double gsmnum;

	private Date imppmsymd;

	private String insymdhms;

	private String insnam;

	private String inskbn;

	private String insmethodkbn;

	private Long updeac;

	private String updymdhms;

	private String updnam;

	private String updkbn;

	private String updmethodkbn;

	// Constructors

	/** default constructor */
	public Lvbtodritm() {
	}

	/** minimal constructor */
	public Lvbtodritm(LvbtodritmId id) {
		this.id = id;
	}

	/** full constructor */
	public Lvbtodritm(LvbtodritmId id, String dtlnum, String itmcod,
			String vitmcod, String itmnam, Long nbrcnt, String nbrunicod,
			Long scdnbrcnt, String scdnbrunicod, Long delcmpcnt,
			String delcmpcntcod, String frekndclacod, String comopecod,
			String cnttmptypcod, String cnttmpunicod, String cnttmpval,
			String itmtmptypcod, String itmtmpunicod, String itmtmpval,
			String batstanum, String batendnum, String staprdnum,
			String endprdnum, String staitmsrlnum, String enditmsrlnum,
			String stapacnum, String endpacnum, String trsmrkitmnam,
			String puritmnam, Long inseac, String rcvmgtnum, String stggdskbn,
			String indsipnum, String indodrnum, String inddisprowrkcod,
			String odrprokbncod, String indfrtshpnam, String indfrtshpnamcod,
			String frtshpmgtnum, String frtshpchacod, String indsndshpnamcod,
			String indsndshpnam, String rcvitmnam, String rcvartnum,
			String rcvartnam, String endusrnam, String shptrsgdsnum,
			String trsinvbrcnum, String trsmrkitmcod, String itmnam1,
			String itmnam2, String itmnam3, String itmnam4, String mopcod,
			String mopnam1, String mopnam2, String indcapunicod,
			String indwgtunicod, String indcntunicod, String sizunicod,
			Double cnvwgtcnt, String cnvunicod, Double dpswgtcnt,
			Double dpscapcnt, String dpsprcunicod, String dpsunimnycnt,
			Double lodreprcvcnt, String frefirinspsccod,
			Double trspaccapreqcnt, Double trspaccaprepcnt,
			String lughndtrmnam1, String lughndtrmnam2, String dtlrmknam1,
			String dtlrmknam2, String dtlrmknam3, String dtlrmknam4,
			Date frepstymd, String frepsthms, String pstpntcod,
			String pstpntnam, String stcnum, String stcdvycod, String boxnum,
			String rcvtmpsrgplccod, String rcvtmpdcnplccod,
			String rcvitmclscod, String itmclscod, String rcvbssspcnam,
			String rcvaddspcnam, String itmadrnam, String stdcod,
			Date mfcreqymd, Date mfcrephms, String lcspltnum, String jancod,
			String itfcod, String lotnum, String lotreqnum, String lotrepnum,
			Date mfcymd, String mfchms, String homenam, String mfcftrnum,
			Date bstbfrymd, String bstbfrhms, Date expymd, String exphms,
			String gdsstgfil, String qltdeftypcod, String qltkbn,
			String setgdsadrnam, String indrcvnum, String lotregpsccod,
			String inoutfretypcod, Date reqbstbfrymd, String reqbstbfrhms,
			Date reqexpymd, String reqexphms, Date repbstbfrymd,
			String repbstbfrhms, Date repexpymd, String repexphms,
			String stkoutcod, String unilodcod, String unilodreqcnt,
			String unilodrepcnt, Long unilodlodcnt, Long reqnumcnt,
			Long repnumcnt, Double purnumcnt, String oneunicod, Long oneinscnt,
			Long onereqcnt, Long onerepcnt, Double cnvcofcnt, String wrpcnt,
			String wrpnumnum, String ctnamtunicod, Double reqcnt,
			Double repcnt, Double wrpinscnt, Double itmlngsizcnt,
			Double itmbldsizcnt, Double itmhgtsizcnt, String grdnam,
			Double slsuniprcspamn, Double bscunisvamn, String srgtmptypcod,
			String grdcod, String clrcod, String clrnam, String sizcod,
			String inseamcod, Double itmwgtcnt, Double gsmnum, Date imppmsymd,
			String insymdhms, String insnam, String inskbn,
			String insmethodkbn, Long updeac, String updymdhms, String updnam,
			String updkbn, String updmethodkbn) {
		this.id = id;
		this.dtlnum = dtlnum;
		this.itmcod = itmcod;
		this.vitmcod = vitmcod;
		this.itmnam = itmnam;
		this.nbrcnt = nbrcnt;
		this.nbrunicod = nbrunicod;
		this.scdnbrcnt = scdnbrcnt;
		this.scdnbrunicod = scdnbrunicod;
		this.delcmpcnt = delcmpcnt;
		this.delcmpcntcod = delcmpcntcod;
		this.frekndclacod = frekndclacod;
		this.comopecod = comopecod;
		this.cnttmptypcod = cnttmptypcod;
		this.cnttmpunicod = cnttmpunicod;
		this.cnttmpval = cnttmpval;
		this.itmtmptypcod = itmtmptypcod;
		this.itmtmpunicod = itmtmpunicod;
		this.itmtmpval = itmtmpval;
		this.batstanum = batstanum;
		this.batendnum = batendnum;
		this.staprdnum = staprdnum;
		this.endprdnum = endprdnum;
		this.staitmsrlnum = staitmsrlnum;
		this.enditmsrlnum = enditmsrlnum;
		this.stapacnum = stapacnum;
		this.endpacnum = endpacnum;
		this.trsmrkitmnam = trsmrkitmnam;
		this.puritmnam = puritmnam;
		this.inseac = inseac;
		this.rcvmgtnum = rcvmgtnum;
		this.stggdskbn = stggdskbn;
		this.indsipnum = indsipnum;
		this.indodrnum = indodrnum;
		this.inddisprowrkcod = inddisprowrkcod;
		this.odrprokbncod = odrprokbncod;
		this.indfrtshpnam = indfrtshpnam;
		this.indfrtshpnamcod = indfrtshpnamcod;
		this.frtshpmgtnum = frtshpmgtnum;
		this.frtshpchacod = frtshpchacod;
		this.indsndshpnamcod = indsndshpnamcod;
		this.indsndshpnam = indsndshpnam;
		this.rcvitmnam = rcvitmnam;
		this.rcvartnum = rcvartnum;
		this.rcvartnam = rcvartnam;
		this.endusrnam = endusrnam;
		this.shptrsgdsnum = shptrsgdsnum;
		this.trsinvbrcnum = trsinvbrcnum;
		this.trsmrkitmcod = trsmrkitmcod;
		this.itmnam1 = itmnam1;
		this.itmnam2 = itmnam2;
		this.itmnam3 = itmnam3;
		this.itmnam4 = itmnam4;
		this.mopcod = mopcod;
		this.mopnam1 = mopnam1;
		this.mopnam2 = mopnam2;
		this.indcapunicod = indcapunicod;
		this.indwgtunicod = indwgtunicod;
		this.indcntunicod = indcntunicod;
		this.sizunicod = sizunicod;
		this.cnvwgtcnt = cnvwgtcnt;
		this.cnvunicod = cnvunicod;
		this.dpswgtcnt = dpswgtcnt;
		this.dpscapcnt = dpscapcnt;
		this.dpsprcunicod = dpsprcunicod;
		this.dpsunimnycnt = dpsunimnycnt;
		this.lodreprcvcnt = lodreprcvcnt;
		this.frefirinspsccod = frefirinspsccod;
		this.trspaccapreqcnt = trspaccapreqcnt;
		this.trspaccaprepcnt = trspaccaprepcnt;
		this.lughndtrmnam1 = lughndtrmnam1;
		this.lughndtrmnam2 = lughndtrmnam2;
		this.dtlrmknam1 = dtlrmknam1;
		this.dtlrmknam2 = dtlrmknam2;
		this.dtlrmknam3 = dtlrmknam3;
		this.dtlrmknam4 = dtlrmknam4;
		this.frepstymd = frepstymd;
		this.frepsthms = frepsthms;
		this.pstpntcod = pstpntcod;
		this.pstpntnam = pstpntnam;
		this.stcnum = stcnum;
		this.stcdvycod = stcdvycod;
		this.boxnum = boxnum;
		this.rcvtmpsrgplccod = rcvtmpsrgplccod;
		this.rcvtmpdcnplccod = rcvtmpdcnplccod;
		this.rcvitmclscod = rcvitmclscod;
		this.itmclscod = itmclscod;
		this.rcvbssspcnam = rcvbssspcnam;
		this.rcvaddspcnam = rcvaddspcnam;
		this.itmadrnam = itmadrnam;
		this.stdcod = stdcod;
		this.mfcreqymd = mfcreqymd;
		this.mfcrephms = mfcrephms;
		this.lcspltnum = lcspltnum;
		this.jancod = jancod;
		this.itfcod = itfcod;
		this.lotnum = lotnum;
		this.lotreqnum = lotreqnum;
		this.lotrepnum = lotrepnum;
		this.mfcymd = mfcymd;
		this.mfchms = mfchms;
		this.homenam = homenam;
		this.mfcftrnum = mfcftrnum;
		this.bstbfrymd = bstbfrymd;
		this.bstbfrhms = bstbfrhms;
		this.expymd = expymd;
		this.exphms = exphms;
		this.gdsstgfil = gdsstgfil;
		this.qltdeftypcod = qltdeftypcod;
		this.qltkbn = qltkbn;
		this.setgdsadrnam = setgdsadrnam;
		this.indrcvnum = indrcvnum;
		this.lotregpsccod = lotregpsccod;
		this.inoutfretypcod = inoutfretypcod;
		this.reqbstbfrymd = reqbstbfrymd;
		this.reqbstbfrhms = reqbstbfrhms;
		this.reqexpymd = reqexpymd;
		this.reqexphms = reqexphms;
		this.repbstbfrymd = repbstbfrymd;
		this.repbstbfrhms = repbstbfrhms;
		this.repexpymd = repexpymd;
		this.repexphms = repexphms;
		this.stkoutcod = stkoutcod;
		this.unilodcod = unilodcod;
		this.unilodreqcnt = unilodreqcnt;
		this.unilodrepcnt = unilodrepcnt;
		this.unilodlodcnt = unilodlodcnt;
		this.reqnumcnt = reqnumcnt;
		this.repnumcnt = repnumcnt;
		this.purnumcnt = purnumcnt;
		this.oneunicod = oneunicod;
		this.oneinscnt = oneinscnt;
		this.onereqcnt = onereqcnt;
		this.onerepcnt = onerepcnt;
		this.cnvcofcnt = cnvcofcnt;
		this.wrpcnt = wrpcnt;
		this.wrpnumnum = wrpnumnum;
		this.ctnamtunicod = ctnamtunicod;
		this.reqcnt = reqcnt;
		this.repcnt = repcnt;
		this.wrpinscnt = wrpinscnt;
		this.itmlngsizcnt = itmlngsizcnt;
		this.itmbldsizcnt = itmbldsizcnt;
		this.itmhgtsizcnt = itmhgtsizcnt;
		this.grdnam = grdnam;
		this.slsuniprcspamn = slsuniprcspamn;
		this.bscunisvamn = bscunisvamn;
		this.srgtmptypcod = srgtmptypcod;
		this.grdcod = grdcod;
		this.clrcod = clrcod;
		this.clrnam = clrnam;
		this.sizcod = sizcod;
		this.inseamcod = inseamcod;
		this.itmwgtcnt = itmwgtcnt;
		this.gsmnum = gsmnum;
		this.imppmsymd = imppmsymd;
		this.insymdhms = insymdhms;
		this.insnam = insnam;
		this.inskbn = inskbn;
		this.insmethodkbn = insmethodkbn;
		this.updeac = updeac;
		this.updymdhms = updymdhms;
		this.updnam = updnam;
		this.updkbn = updkbn;
		this.updmethodkbn = updmethodkbn;
	}

	// Property accessors

	public LvbtodritmId getId() {
		return this.id;
	}

	public void setId(LvbtodritmId id) {
		this.id = id;
	}

	public String getDtlnum() {
		return this.dtlnum;
	}

	public void setDtlnum(String dtlnum) {
		this.dtlnum = dtlnum;
	}

	public String getItmcod() {
		return this.itmcod;
	}

	public void setItmcod(String itmcod) {
		this.itmcod = itmcod;
	}

	public String getVitmcod() {
		return this.vitmcod;
	}

	public void setVitmcod(String vitmcod) {
		this.vitmcod = vitmcod;
	}

	public String getItmnam() {
		return this.itmnam;
	}

	public void setItmnam(String itmnam) {
		this.itmnam = itmnam;
	}

	public Long getNbrcnt() {
		return this.nbrcnt;
	}

	public void setNbrcnt(Long nbrcnt) {
		this.nbrcnt = nbrcnt;
	}

	public String getNbrunicod() {
		return this.nbrunicod;
	}

	public void setNbrunicod(String nbrunicod) {
		this.nbrunicod = nbrunicod;
	}

	public Long getScdnbrcnt() {
		return this.scdnbrcnt;
	}

	public void setScdnbrcnt(Long scdnbrcnt) {
		this.scdnbrcnt = scdnbrcnt;
	}

	public String getScdnbrunicod() {
		return this.scdnbrunicod;
	}

	public void setScdnbrunicod(String scdnbrunicod) {
		this.scdnbrunicod = scdnbrunicod;
	}

	public Long getDelcmpcnt() {
		return this.delcmpcnt;
	}

	public void setDelcmpcnt(Long delcmpcnt) {
		this.delcmpcnt = delcmpcnt;
	}

	public String getDelcmpcntcod() {
		return this.delcmpcntcod;
	}

	public void setDelcmpcntcod(String delcmpcntcod) {
		this.delcmpcntcod = delcmpcntcod;
	}

	public String getFrekndclacod() {
		return this.frekndclacod;
	}

	public void setFrekndclacod(String frekndclacod) {
		this.frekndclacod = frekndclacod;
	}

	public String getComopecod() {
		return this.comopecod;
	}

	public void setComopecod(String comopecod) {
		this.comopecod = comopecod;
	}

	public String getCnttmptypcod() {
		return this.cnttmptypcod;
	}

	public void setCnttmptypcod(String cnttmptypcod) {
		this.cnttmptypcod = cnttmptypcod;
	}

	public String getCnttmpunicod() {
		return this.cnttmpunicod;
	}

	public void setCnttmpunicod(String cnttmpunicod) {
		this.cnttmpunicod = cnttmpunicod;
	}

	public String getCnttmpval() {
		return this.cnttmpval;
	}

	public void setCnttmpval(String cnttmpval) {
		this.cnttmpval = cnttmpval;
	}

	public String getItmtmptypcod() {
		return this.itmtmptypcod;
	}

	public void setItmtmptypcod(String itmtmptypcod) {
		this.itmtmptypcod = itmtmptypcod;
	}

	public String getItmtmpunicod() {
		return this.itmtmpunicod;
	}

	public void setItmtmpunicod(String itmtmpunicod) {
		this.itmtmpunicod = itmtmpunicod;
	}

	public String getItmtmpval() {
		return this.itmtmpval;
	}

	public void setItmtmpval(String itmtmpval) {
		this.itmtmpval = itmtmpval;
	}

	public String getBatstanum() {
		return this.batstanum;
	}

	public void setBatstanum(String batstanum) {
		this.batstanum = batstanum;
	}

	public String getBatendnum() {
		return this.batendnum;
	}

	public void setBatendnum(String batendnum) {
		this.batendnum = batendnum;
	}

	public String getStaprdnum() {
		return this.staprdnum;
	}

	public void setStaprdnum(String staprdnum) {
		this.staprdnum = staprdnum;
	}

	public String getEndprdnum() {
		return this.endprdnum;
	}

	public void setEndprdnum(String endprdnum) {
		this.endprdnum = endprdnum;
	}

	public String getStaitmsrlnum() {
		return this.staitmsrlnum;
	}

	public void setStaitmsrlnum(String staitmsrlnum) {
		this.staitmsrlnum = staitmsrlnum;
	}

	public String getEnditmsrlnum() {
		return this.enditmsrlnum;
	}

	public void setEnditmsrlnum(String enditmsrlnum) {
		this.enditmsrlnum = enditmsrlnum;
	}

	public String getStapacnum() {
		return this.stapacnum;
	}

	public void setStapacnum(String stapacnum) {
		this.stapacnum = stapacnum;
	}

	public String getEndpacnum() {
		return this.endpacnum;
	}

	public void setEndpacnum(String endpacnum) {
		this.endpacnum = endpacnum;
	}

	public String getTrsmrkitmnam() {
		return this.trsmrkitmnam;
	}

	public void setTrsmrkitmnam(String trsmrkitmnam) {
		this.trsmrkitmnam = trsmrkitmnam;
	}

	public String getPuritmnam() {
		return this.puritmnam;
	}

	public void setPuritmnam(String puritmnam) {
		this.puritmnam = puritmnam;
	}

	public Long getInseac() {
		return this.inseac;
	}

	public void setInseac(Long inseac) {
		this.inseac = inseac;
	}

	public String getRcvmgtnum() {
		return this.rcvmgtnum;
	}

	public void setRcvmgtnum(String rcvmgtnum) {
		this.rcvmgtnum = rcvmgtnum;
	}

	public String getStggdskbn() {
		return this.stggdskbn;
	}

	public void setStggdskbn(String stggdskbn) {
		this.stggdskbn = stggdskbn;
	}

	public String getIndsipnum() {
		return this.indsipnum;
	}

	public void setIndsipnum(String indsipnum) {
		this.indsipnum = indsipnum;
	}

	public String getIndodrnum() {
		return this.indodrnum;
	}

	public void setIndodrnum(String indodrnum) {
		this.indodrnum = indodrnum;
	}

	public String getInddisprowrkcod() {
		return this.inddisprowrkcod;
	}

	public void setInddisprowrkcod(String inddisprowrkcod) {
		this.inddisprowrkcod = inddisprowrkcod;
	}

	public String getOdrprokbncod() {
		return this.odrprokbncod;
	}

	public void setOdrprokbncod(String odrprokbncod) {
		this.odrprokbncod = odrprokbncod;
	}

	public String getIndfrtshpnam() {
		return this.indfrtshpnam;
	}

	public void setIndfrtshpnam(String indfrtshpnam) {
		this.indfrtshpnam = indfrtshpnam;
	}

	public String getIndfrtshpnamcod() {
		return this.indfrtshpnamcod;
	}

	public void setIndfrtshpnamcod(String indfrtshpnamcod) {
		this.indfrtshpnamcod = indfrtshpnamcod;
	}

	public String getFrtshpmgtnum() {
		return this.frtshpmgtnum;
	}

	public void setFrtshpmgtnum(String frtshpmgtnum) {
		this.frtshpmgtnum = frtshpmgtnum;
	}

	public String getFrtshpchacod() {
		return this.frtshpchacod;
	}

	public void setFrtshpchacod(String frtshpchacod) {
		this.frtshpchacod = frtshpchacod;
	}

	public String getIndsndshpnamcod() {
		return this.indsndshpnamcod;
	}

	public void setIndsndshpnamcod(String indsndshpnamcod) {
		this.indsndshpnamcod = indsndshpnamcod;
	}

	public String getIndsndshpnam() {
		return this.indsndshpnam;
	}

	public void setIndsndshpnam(String indsndshpnam) {
		this.indsndshpnam = indsndshpnam;
	}

	public String getRcvitmnam() {
		return this.rcvitmnam;
	}

	public void setRcvitmnam(String rcvitmnam) {
		this.rcvitmnam = rcvitmnam;
	}

	public String getRcvartnum() {
		return this.rcvartnum;
	}

	public void setRcvartnum(String rcvartnum) {
		this.rcvartnum = rcvartnum;
	}

	public String getRcvartnam() {
		return this.rcvartnam;
	}

	public void setRcvartnam(String rcvartnam) {
		this.rcvartnam = rcvartnam;
	}

	public String getEndusrnam() {
		return this.endusrnam;
	}

	public void setEndusrnam(String endusrnam) {
		this.endusrnam = endusrnam;
	}

	public String getShptrsgdsnum() {
		return this.shptrsgdsnum;
	}

	public void setShptrsgdsnum(String shptrsgdsnum) {
		this.shptrsgdsnum = shptrsgdsnum;
	}

	public String getTrsinvbrcnum() {
		return this.trsinvbrcnum;
	}

	public void setTrsinvbrcnum(String trsinvbrcnum) {
		this.trsinvbrcnum = trsinvbrcnum;
	}

	public String getTrsmrkitmcod() {
		return this.trsmrkitmcod;
	}

	public void setTrsmrkitmcod(String trsmrkitmcod) {
		this.trsmrkitmcod = trsmrkitmcod;
	}

	public String getItmnam1() {
		return this.itmnam1;
	}

	public void setItmnam1(String itmnam1) {
		this.itmnam1 = itmnam1;
	}

	public String getItmnam2() {
		return this.itmnam2;
	}

	public void setItmnam2(String itmnam2) {
		this.itmnam2 = itmnam2;
	}

	public String getItmnam3() {
		return this.itmnam3;
	}

	public void setItmnam3(String itmnam3) {
		this.itmnam3 = itmnam3;
	}

	public String getItmnam4() {
		return this.itmnam4;
	}

	public void setItmnam4(String itmnam4) {
		this.itmnam4 = itmnam4;
	}

	public String getMopcod() {
		return this.mopcod;
	}

	public void setMopcod(String mopcod) {
		this.mopcod = mopcod;
	}

	public String getMopnam1() {
		return this.mopnam1;
	}

	public void setMopnam1(String mopnam1) {
		this.mopnam1 = mopnam1;
	}

	public String getMopnam2() {
		return this.mopnam2;
	}

	public void setMopnam2(String mopnam2) {
		this.mopnam2 = mopnam2;
	}

	public String getIndcapunicod() {
		return this.indcapunicod;
	}

	public void setIndcapunicod(String indcapunicod) {
		this.indcapunicod = indcapunicod;
	}

	public String getIndwgtunicod() {
		return this.indwgtunicod;
	}

	public void setIndwgtunicod(String indwgtunicod) {
		this.indwgtunicod = indwgtunicod;
	}

	public String getIndcntunicod() {
		return this.indcntunicod;
	}

	public void setIndcntunicod(String indcntunicod) {
		this.indcntunicod = indcntunicod;
	}

	public String getSizunicod() {
		return this.sizunicod;
	}

	public void setSizunicod(String sizunicod) {
		this.sizunicod = sizunicod;
	}

	public Double getCnvwgtcnt() {
		return this.cnvwgtcnt;
	}

	public void setCnvwgtcnt(Double cnvwgtcnt) {
		this.cnvwgtcnt = cnvwgtcnt;
	}

	public String getCnvunicod() {
		return this.cnvunicod;
	}

	public void setCnvunicod(String cnvunicod) {
		this.cnvunicod = cnvunicod;
	}

	public Double getDpswgtcnt() {
		return this.dpswgtcnt;
	}

	public void setDpswgtcnt(Double dpswgtcnt) {
		this.dpswgtcnt = dpswgtcnt;
	}

	public Double getDpscapcnt() {
		return this.dpscapcnt;
	}

	public void setDpscapcnt(Double dpscapcnt) {
		this.dpscapcnt = dpscapcnt;
	}

	public String getDpsprcunicod() {
		return this.dpsprcunicod;
	}

	public void setDpsprcunicod(String dpsprcunicod) {
		this.dpsprcunicod = dpsprcunicod;
	}

	public String getDpsunimnycnt() {
		return this.dpsunimnycnt;
	}

	public void setDpsunimnycnt(String dpsunimnycnt) {
		this.dpsunimnycnt = dpsunimnycnt;
	}

	public Double getLodreprcvcnt() {
		return this.lodreprcvcnt;
	}

	public void setLodreprcvcnt(Double lodreprcvcnt) {
		this.lodreprcvcnt = lodreprcvcnt;
	}

	public String getFrefirinspsccod() {
		return this.frefirinspsccod;
	}

	public void setFrefirinspsccod(String frefirinspsccod) {
		this.frefirinspsccod = frefirinspsccod;
	}

	public Double getTrspaccapreqcnt() {
		return this.trspaccapreqcnt;
	}

	public void setTrspaccapreqcnt(Double trspaccapreqcnt) {
		this.trspaccapreqcnt = trspaccapreqcnt;
	}

	public Double getTrspaccaprepcnt() {
		return this.trspaccaprepcnt;
	}

	public void setTrspaccaprepcnt(Double trspaccaprepcnt) {
		this.trspaccaprepcnt = trspaccaprepcnt;
	}

	public String getLughndtrmnam1() {
		return this.lughndtrmnam1;
	}

	public void setLughndtrmnam1(String lughndtrmnam1) {
		this.lughndtrmnam1 = lughndtrmnam1;
	}

	public String getLughndtrmnam2() {
		return this.lughndtrmnam2;
	}

	public void setLughndtrmnam2(String lughndtrmnam2) {
		this.lughndtrmnam2 = lughndtrmnam2;
	}

	public String getDtlrmknam1() {
		return this.dtlrmknam1;
	}

	public void setDtlrmknam1(String dtlrmknam1) {
		this.dtlrmknam1 = dtlrmknam1;
	}

	public String getDtlrmknam2() {
		return this.dtlrmknam2;
	}

	public void setDtlrmknam2(String dtlrmknam2) {
		this.dtlrmknam2 = dtlrmknam2;
	}

	public String getDtlrmknam3() {
		return this.dtlrmknam3;
	}

	public void setDtlrmknam3(String dtlrmknam3) {
		this.dtlrmknam3 = dtlrmknam3;
	}

	public String getDtlrmknam4() {
		return this.dtlrmknam4;
	}

	public void setDtlrmknam4(String dtlrmknam4) {
		this.dtlrmknam4 = dtlrmknam4;
	}

	public Date getFrepstymd() {
		return this.frepstymd;
	}

	public void setFrepstymd(Date frepstymd) {
		this.frepstymd = frepstymd;
	}

	public String getFrepsthms() {
		return this.frepsthms;
	}

	public void setFrepsthms(String frepsthms) {
		this.frepsthms = frepsthms;
	}

	public String getPstpntcod() {
		return this.pstpntcod;
	}

	public void setPstpntcod(String pstpntcod) {
		this.pstpntcod = pstpntcod;
	}

	public String getPstpntnam() {
		return this.pstpntnam;
	}

	public void setPstpntnam(String pstpntnam) {
		this.pstpntnam = pstpntnam;
	}

	public String getStcnum() {
		return this.stcnum;
	}

	public void setStcnum(String stcnum) {
		this.stcnum = stcnum;
	}

	public String getStcdvycod() {
		return this.stcdvycod;
	}

	public void setStcdvycod(String stcdvycod) {
		this.stcdvycod = stcdvycod;
	}

	public String getBoxnum() {
		return this.boxnum;
	}

	public void setBoxnum(String boxnum) {
		this.boxnum = boxnum;
	}

	public String getRcvtmpsrgplccod() {
		return this.rcvtmpsrgplccod;
	}

	public void setRcvtmpsrgplccod(String rcvtmpsrgplccod) {
		this.rcvtmpsrgplccod = rcvtmpsrgplccod;
	}

	public String getRcvtmpdcnplccod() {
		return this.rcvtmpdcnplccod;
	}

	public void setRcvtmpdcnplccod(String rcvtmpdcnplccod) {
		this.rcvtmpdcnplccod = rcvtmpdcnplccod;
	}

	public String getRcvitmclscod() {
		return this.rcvitmclscod;
	}

	public void setRcvitmclscod(String rcvitmclscod) {
		this.rcvitmclscod = rcvitmclscod;
	}

	public String getItmclscod() {
		return this.itmclscod;
	}

	public void setItmclscod(String itmclscod) {
		this.itmclscod = itmclscod;
	}

	public String getRcvbssspcnam() {
		return this.rcvbssspcnam;
	}

	public void setRcvbssspcnam(String rcvbssspcnam) {
		this.rcvbssspcnam = rcvbssspcnam;
	}

	public String getRcvaddspcnam() {
		return this.rcvaddspcnam;
	}

	public void setRcvaddspcnam(String rcvaddspcnam) {
		this.rcvaddspcnam = rcvaddspcnam;
	}

	public String getItmadrnam() {
		return this.itmadrnam;
	}

	public void setItmadrnam(String itmadrnam) {
		this.itmadrnam = itmadrnam;
	}

	public String getStdcod() {
		return this.stdcod;
	}

	public void setStdcod(String stdcod) {
		this.stdcod = stdcod;
	}

	public Date getMfcreqymd() {
		return this.mfcreqymd;
	}

	public void setMfcreqymd(Date mfcreqymd) {
		this.mfcreqymd = mfcreqymd;
	}

	public Date getMfcrephms() {
		return this.mfcrephms;
	}

	public void setMfcrephms(Date mfcrephms) {
		this.mfcrephms = mfcrephms;
	}

	public String getLcspltnum() {
		return this.lcspltnum;
	}

	public void setLcspltnum(String lcspltnum) {
		this.lcspltnum = lcspltnum;
	}

	public String getJancod() {
		return this.jancod;
	}

	public void setJancod(String jancod) {
		this.jancod = jancod;
	}

	public String getItfcod() {
		return this.itfcod;
	}

	public void setItfcod(String itfcod) {
		this.itfcod = itfcod;
	}

	public String getLotnum() {
		return this.lotnum;
	}

	public void setLotnum(String lotnum) {
		this.lotnum = lotnum;
	}

	public String getLotreqnum() {
		return this.lotreqnum;
	}

	public void setLotreqnum(String lotreqnum) {
		this.lotreqnum = lotreqnum;
	}

	public String getLotrepnum() {
		return this.lotrepnum;
	}

	public void setLotrepnum(String lotrepnum) {
		this.lotrepnum = lotrepnum;
	}

	public Date getMfcymd() {
		return this.mfcymd;
	}

	public void setMfcymd(Date mfcymd) {
		this.mfcymd = mfcymd;
	}

	public String getMfchms() {
		return this.mfchms;
	}

	public void setMfchms(String mfchms) {
		this.mfchms = mfchms;
	}

	public String getHomenam() {
		return this.homenam;
	}

	public void setHomenam(String homenam) {
		this.homenam = homenam;
	}

	public String getMfcftrnum() {
		return this.mfcftrnum;
	}

	public void setMfcftrnum(String mfcftrnum) {
		this.mfcftrnum = mfcftrnum;
	}

	public Date getBstbfrymd() {
		return this.bstbfrymd;
	}

	public void setBstbfrymd(Date bstbfrymd) {
		this.bstbfrymd = bstbfrymd;
	}

	public String getBstbfrhms() {
		return this.bstbfrhms;
	}

	public void setBstbfrhms(String bstbfrhms) {
		this.bstbfrhms = bstbfrhms;
	}

	public Date getExpymd() {
		return this.expymd;
	}

	public void setExpymd(Date expymd) {
		this.expymd = expymd;
	}

	public String getExphms() {
		return this.exphms;
	}

	public void setExphms(String exphms) {
		this.exphms = exphms;
	}

	public String getGdsstgfil() {
		return this.gdsstgfil;
	}

	public void setGdsstgfil(String gdsstgfil) {
		this.gdsstgfil = gdsstgfil;
	}

	public String getQltdeftypcod() {
		return this.qltdeftypcod;
	}

	public void setQltdeftypcod(String qltdeftypcod) {
		this.qltdeftypcod = qltdeftypcod;
	}

	public String getQltkbn() {
		return this.qltkbn;
	}

	public void setQltkbn(String qltkbn) {
		this.qltkbn = qltkbn;
	}

	public String getSetgdsadrnam() {
		return this.setgdsadrnam;
	}

	public void setSetgdsadrnam(String setgdsadrnam) {
		this.setgdsadrnam = setgdsadrnam;
	}

	public String getIndrcvnum() {
		return this.indrcvnum;
	}

	public void setIndrcvnum(String indrcvnum) {
		this.indrcvnum = indrcvnum;
	}

	public String getLotregpsccod() {
		return this.lotregpsccod;
	}

	public void setLotregpsccod(String lotregpsccod) {
		this.lotregpsccod = lotregpsccod;
	}

	public String getInoutfretypcod() {
		return this.inoutfretypcod;
	}

	public void setInoutfretypcod(String inoutfretypcod) {
		this.inoutfretypcod = inoutfretypcod;
	}

	public Date getReqbstbfrymd() {
		return this.reqbstbfrymd;
	}

	public void setReqbstbfrymd(Date reqbstbfrymd) {
		this.reqbstbfrymd = reqbstbfrymd;
	}

	public String getReqbstbfrhms() {
		return this.reqbstbfrhms;
	}

	public void setReqbstbfrhms(String reqbstbfrhms) {
		this.reqbstbfrhms = reqbstbfrhms;
	}

	public Date getReqexpymd() {
		return this.reqexpymd;
	}

	public void setReqexpymd(Date reqexpymd) {
		this.reqexpymd = reqexpymd;
	}

	public String getReqexphms() {
		return this.reqexphms;
	}

	public void setReqexphms(String reqexphms) {
		this.reqexphms = reqexphms;
	}

	public Date getRepbstbfrymd() {
		return this.repbstbfrymd;
	}

	public void setRepbstbfrymd(Date repbstbfrymd) {
		this.repbstbfrymd = repbstbfrymd;
	}

	public String getRepbstbfrhms() {
		return this.repbstbfrhms;
	}

	public void setRepbstbfrhms(String repbstbfrhms) {
		this.repbstbfrhms = repbstbfrhms;
	}

	public Date getRepexpymd() {
		return this.repexpymd;
	}

	public void setRepexpymd(Date repexpymd) {
		this.repexpymd = repexpymd;
	}

	public String getRepexphms() {
		return this.repexphms;
	}

	public void setRepexphms(String repexphms) {
		this.repexphms = repexphms;
	}

	public String getStkoutcod() {
		return this.stkoutcod;
	}

	public void setStkoutcod(String stkoutcod) {
		this.stkoutcod = stkoutcod;
	}

	public String getUnilodcod() {
		return this.unilodcod;
	}

	public void setUnilodcod(String unilodcod) {
		this.unilodcod = unilodcod;
	}

	public String getUnilodreqcnt() {
		return this.unilodreqcnt;
	}

	public void setUnilodreqcnt(String unilodreqcnt) {
		this.unilodreqcnt = unilodreqcnt;
	}

	public String getUnilodrepcnt() {
		return this.unilodrepcnt;
	}

	public void setUnilodrepcnt(String unilodrepcnt) {
		this.unilodrepcnt = unilodrepcnt;
	}

	public Long getUnilodlodcnt() {
		return this.unilodlodcnt;
	}

	public void setUnilodlodcnt(Long unilodlodcnt) {
		this.unilodlodcnt = unilodlodcnt;
	}

	public Long getReqnumcnt() {
		return this.reqnumcnt;
	}

	public void setReqnumcnt(Long reqnumcnt) {
		this.reqnumcnt = reqnumcnt;
	}

	public Long getRepnumcnt() {
		return this.repnumcnt;
	}

	public void setRepnumcnt(Long repnumcnt) {
		this.repnumcnt = repnumcnt;
	}

	public Double getPurnumcnt() {
		return this.purnumcnt;
	}

	public void setPurnumcnt(Double purnumcnt) {
		this.purnumcnt = purnumcnt;
	}

	public String getOneunicod() {
		return this.oneunicod;
	}

	public void setOneunicod(String oneunicod) {
		this.oneunicod = oneunicod;
	}

	public Long getOneinscnt() {
		return this.oneinscnt;
	}

	public void setOneinscnt(Long oneinscnt) {
		this.oneinscnt = oneinscnt;
	}

	public Long getOnereqcnt() {
		return this.onereqcnt;
	}

	public void setOnereqcnt(Long onereqcnt) {
		this.onereqcnt = onereqcnt;
	}

	public Long getOnerepcnt() {
		return this.onerepcnt;
	}

	public void setOnerepcnt(Long onerepcnt) {
		this.onerepcnt = onerepcnt;
	}

	public Double getCnvcofcnt() {
		return this.cnvcofcnt;
	}

	public void setCnvcofcnt(Double cnvcofcnt) {
		this.cnvcofcnt = cnvcofcnt;
	}

	public String getWrpcnt() {
		return this.wrpcnt;
	}

	public void setWrpcnt(String wrpcnt) {
		this.wrpcnt = wrpcnt;
	}

	public String getWrpnumnum() {
		return this.wrpnumnum;
	}

	public void setWrpnumnum(String wrpnumnum) {
		this.wrpnumnum = wrpnumnum;
	}

	public String getCtnamtunicod() {
		return this.ctnamtunicod;
	}

	public void setCtnamtunicod(String ctnamtunicod) {
		this.ctnamtunicod = ctnamtunicod;
	}

	public Double getReqcnt() {
		return this.reqcnt;
	}

	public void setReqcnt(Double reqcnt) {
		this.reqcnt = reqcnt;
	}

	public Double getRepcnt() {
		return this.repcnt;
	}

	public void setRepcnt(Double repcnt) {
		this.repcnt = repcnt;
	}

	public Double getWrpinscnt() {
		return this.wrpinscnt;
	}

	public void setWrpinscnt(Double wrpinscnt) {
		this.wrpinscnt = wrpinscnt;
	}

	public Double getItmlngsizcnt() {
		return this.itmlngsizcnt;
	}

	public void setItmlngsizcnt(Double itmlngsizcnt) {
		this.itmlngsizcnt = itmlngsizcnt;
	}

	public Double getItmbldsizcnt() {
		return this.itmbldsizcnt;
	}

	public void setItmbldsizcnt(Double itmbldsizcnt) {
		this.itmbldsizcnt = itmbldsizcnt;
	}

	public Double getItmhgtsizcnt() {
		return this.itmhgtsizcnt;
	}

	public void setItmhgtsizcnt(Double itmhgtsizcnt) {
		this.itmhgtsizcnt = itmhgtsizcnt;
	}

	public String getGrdnam() {
		return this.grdnam;
	}

	public void setGrdnam(String grdnam) {
		this.grdnam = grdnam;
	}

	public Double getSlsuniprcspamn() {
		return this.slsuniprcspamn;
	}

	public void setSlsuniprcspamn(Double slsuniprcspamn) {
		this.slsuniprcspamn = slsuniprcspamn;
	}

	public Double getBscunisvamn() {
		return this.bscunisvamn;
	}

	public void setBscunisvamn(Double bscunisvamn) {
		this.bscunisvamn = bscunisvamn;
	}

	public String getSrgtmptypcod() {
		return this.srgtmptypcod;
	}

	public void setSrgtmptypcod(String srgtmptypcod) {
		this.srgtmptypcod = srgtmptypcod;
	}

	public String getGrdcod() {
		return this.grdcod;
	}

	public void setGrdcod(String grdcod) {
		this.grdcod = grdcod;
	}

	public String getClrcod() {
		return this.clrcod;
	}

	public void setClrcod(String clrcod) {
		this.clrcod = clrcod;
	}

	public String getClrnam() {
		return this.clrnam;
	}

	public void setClrnam(String clrnam) {
		this.clrnam = clrnam;
	}

	public String getSizcod() {
		return this.sizcod;
	}

	public void setSizcod(String sizcod) {
		this.sizcod = sizcod;
	}

	public String getInseamcod() {
		return this.inseamcod;
	}

	public void setInseamcod(String inseamcod) {
		this.inseamcod = inseamcod;
	}

	public Double getItmwgtcnt() {
		return this.itmwgtcnt;
	}

	public void setItmwgtcnt(Double itmwgtcnt) {
		this.itmwgtcnt = itmwgtcnt;
	}

	public Double getGsmnum() {
		return this.gsmnum;
	}

	public void setGsmnum(Double gsmnum) {
		this.gsmnum = gsmnum;
	}

	public Date getImppmsymd() {
		return this.imppmsymd;
	}

	public void setImppmsymd(Date imppmsymd) {
		this.imppmsymd = imppmsymd;
	}

	public String getInsymdhms() {
		return this.insymdhms;
	}

	public void setInsymdhms(String insymdhms) {
		this.insymdhms = insymdhms;
	}

	public String getInsnam() {
		return this.insnam;
	}

	public void setInsnam(String insnam) {
		this.insnam = insnam;
	}

	public String getInskbn() {
		return this.inskbn;
	}

	public void setInskbn(String inskbn) {
		this.inskbn = inskbn;
	}

	public String getInsmethodkbn() {
		return this.insmethodkbn;
	}

	public void setInsmethodkbn(String insmethodkbn) {
		this.insmethodkbn = insmethodkbn;
	}

	public Long getUpdeac() {
		return this.updeac;
	}

	public void setUpdeac(Long updeac) {
		this.updeac = updeac;
	}

	public String getUpdymdhms() {
		return this.updymdhms;
	}

	public void setUpdymdhms(String updymdhms) {
		this.updymdhms = updymdhms;
	}

	public String getUpdnam() {
		return this.updnam;
	}

	public void setUpdnam(String updnam) {
		this.updnam = updnam;
	}

	public String getUpdkbn() {
		return this.updkbn;
	}

	public void setUpdkbn(String updkbn) {
		this.updkbn = updkbn;
	}

	public String getUpdmethodkbn() {
		return this.updmethodkbn;
	}

	public void setUpdmethodkbn(String updmethodkbn) {
		this.updmethodkbn = updmethodkbn;
	}

}