package org.cloud.model;

/**
 * LmmmatrId generated by MyEclipse Persistence Tools
 */

public class LmmmatrId implements java.io.Serializable {

	// Fields

	private String tntcod;

	private String atrgrpcod;

	// Constructors

	/** default constructor */
	public LmmmatrId() {
	}

	/** full constructor */
	public LmmmatrId(String tntcod, String atrgrpcod) {
		this.tntcod = tntcod;
		this.atrgrpcod = atrgrpcod;
	}

	// Property accessors

	public String getTntcod() {
		return this.tntcod;
	}

	public void setTntcod(String tntcod) {
		this.tntcod = tntcod;
	}

	public String getAtrgrpcod() {
		return this.atrgrpcod;
	}

	public void setAtrgrpcod(String atrgrpcod) {
		this.atrgrpcod = atrgrpcod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LmmmatrId))
			return false;
		LmmmatrId castOther = (LmmmatrId) other;

		return ((this.getTntcod() == castOther.getTntcod()) || (this
				.getTntcod() != null
				&& castOther.getTntcod() != null && this.getTntcod().equals(
				castOther.getTntcod())))
				&& ((this.getAtrgrpcod() == castOther.getAtrgrpcod()) || (this
						.getAtrgrpcod() != null
						&& castOther.getAtrgrpcod() != null && this
						.getAtrgrpcod().equals(castOther.getAtrgrpcod())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTntcod() == null ? 0 : this.getTntcod().hashCode());
		result = 37 * result
				+ (getAtrgrpcod() == null ? 0 : this.getAtrgrpcod().hashCode());
		return result;
	}

}