package org.cloud.model;

/**
 * LmmmtrkevtId generated by MyEclipse Persistence Tools
 */

public class LmmmtrkevtId implements java.io.Serializable {

	// Fields

	private String tntcod;

	private String trkgrpcod;

	private String evtcod;

	// Constructors

	/** default constructor */
	public LmmmtrkevtId() {
	}

	/** full constructor */
	public LmmmtrkevtId(String tntcod, String trkgrpcod, String evtcod) {
		this.tntcod = tntcod;
		this.trkgrpcod = trkgrpcod;
		this.evtcod = evtcod;
	}

	// Property accessors

	public String getTntcod() {
		return this.tntcod;
	}

	public void setTntcod(String tntcod) {
		this.tntcod = tntcod;
	}

	public String getTrkgrpcod() {
		return this.trkgrpcod;
	}

	public void setTrkgrpcod(String trkgrpcod) {
		this.trkgrpcod = trkgrpcod;
	}

	public String getEvtcod() {
		return this.evtcod;
	}

	public void setEvtcod(String evtcod) {
		this.evtcod = evtcod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LmmmtrkevtId))
			return false;
		LmmmtrkevtId castOther = (LmmmtrkevtId) other;

		return ((this.getTntcod() == castOther.getTntcod()) || (this
				.getTntcod() != null
				&& castOther.getTntcod() != null && this.getTntcod().equals(
				castOther.getTntcod())))
				&& ((this.getTrkgrpcod() == castOther.getTrkgrpcod()) || (this
						.getTrkgrpcod() != null
						&& castOther.getTrkgrpcod() != null && this
						.getTrkgrpcod().equals(castOther.getTrkgrpcod())))
				&& ((this.getEvtcod() == castOther.getEvtcod()) || (this
						.getEvtcod() != null
						&& castOther.getEvtcod() != null && this.getEvtcod()
						.equals(castOther.getEvtcod())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTntcod() == null ? 0 : this.getTntcod().hashCode());
		result = 37 * result
				+ (getTrkgrpcod() == null ? 0 : this.getTrkgrpcod().hashCode());
		result = 37 * result
				+ (getEvtcod() == null ? 0 : this.getEvtcod().hashCode());
		return result;
	}

}