package org.cloud.model;

/**
 * LmmmusrId generated by MyEclipse Persistence Tools
 */

public class LmmmusrId implements java.io.Serializable {

	// Fields

	private String tntcod;

	private String usrcod;

	// Constructors

	/** default constructor */
	public LmmmusrId() {
	}

	/** full constructor */
	public LmmmusrId(String tntcod, String usrcod) {
		this.tntcod = tntcod;
		this.usrcod = usrcod;
	}

	// Property accessors

	public String getTntcod() {
		return this.tntcod;
	}

	public void setTntcod(String tntcod) {
		this.tntcod = tntcod;
	}

	public String getUsrcod() {
		return this.usrcod;
	}

	public void setUsrcod(String usrcod) {
		this.usrcod = usrcod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LmmmusrId))
			return false;
		LmmmusrId castOther = (LmmmusrId) other;

		return ((this.getTntcod() == castOther.getTntcod()) || (this
				.getTntcod() != null
				&& castOther.getTntcod() != null && this.getTntcod().equals(
				castOther.getTntcod())))
				&& ((this.getUsrcod() == castOther.getUsrcod()) || (this
						.getUsrcod() != null
						&& castOther.getUsrcod() != null && this.getUsrcod()
						.equals(castOther.getUsrcod())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTntcod() == null ? 0 : this.getTntcod().hashCode());
		result = 37 * result
				+ (getUsrcod() == null ? 0 : this.getUsrcod().hashCode());
		return result;
	}

}