package org.cloud.model;

import java.util.Date;

/**
 * Lmmmuser generated by MyEclipse Persistence Tools
 */

public class Lmmmuser implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String userid;

	private String username;

	private String password;

	private String name;

	private Date createdate;

	private Date modificationdate;

	private String telephone;

	private String mobilephone;

	private String department;

	private String position;

	private String remarks;

	// Constructors

	/** default constructor */
	public Lmmmuser() {
	}

	/** full constructor */
	public Lmmmuser(String username, String password, String name,
			Date createdate, Date modificationdate, String telephone,
			String mobilephone, String department, String position,
			String remarks) {
		this.username = username;
		this.password = password;
		this.name = name;
		this.createdate = createdate;
		this.modificationdate = modificationdate;
		this.telephone = telephone;
		this.mobilephone = mobilephone;
		this.department = department;
		this.position = position;
		this.remarks = remarks;
	}

	// Property accessors

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public Date getModificationdate() {
		return this.modificationdate;
	}

	public void setModificationdate(Date modificationdate) {
		this.modificationdate = modificationdate;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getMobilephone() {
		return this.mobilephone;
	}

	public void setMobilephone(String mobilephone) {
		this.mobilephone = mobilephone;
	}

	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}