package org.cloud.model;

/**
 * Lmmmtrkevt generated by MyEclipse Persistence Tools
 */

public class Lmmmtrkevt implements java.io.Serializable {

	// Fields

	private LmmmtrkevtId id;

	private String aboflg;

	private Long rutodrnum;

	private String evtkbn;

	private String evtnam;

	private String altkbn;

	private String evtmrgcod;

	private String evtmrgnam;

	private Long statrstme;

	private String plccod;

	private String plcnam;

	private String refgrpcod;

	private String updgrpcod;

	private String tmeznecod;

	private String apporgcod;

	private String insymdhms;

	private String insnam;

	private String inskbn;

	private String insmethodkbn;

	private Long updeac;

	private String updymdhms;

	private String updnam;

	private String updkbn;

	private String updmethodkbn;

	// Constructors

	/** default constructor */
	public Lmmmtrkevt() {
	}

	/** minimal constructor */
	public Lmmmtrkevt(LmmmtrkevtId id) {
		this.id = id;
	}

	/** full constructor */
	public Lmmmtrkevt(LmmmtrkevtId id, String aboflg, Long rutodrnum,
			String evtkbn, String evtnam, String altkbn, String evtmrgcod,
			String evtmrgnam, Long statrstme, String plccod, String plcnam,
			String refgrpcod, String updgrpcod, String tmeznecod,
			String apporgcod, String insymdhms, String insnam, String inskbn,
			String insmethodkbn, Long updeac, String updymdhms, String updnam,
			String updkbn, String updmethodkbn) {
		this.id = id;
		this.aboflg = aboflg;
		this.rutodrnum = rutodrnum;
		this.evtkbn = evtkbn;
		this.evtnam = evtnam;
		this.altkbn = altkbn;
		this.evtmrgcod = evtmrgcod;
		this.evtmrgnam = evtmrgnam;
		this.statrstme = statrstme;
		this.plccod = plccod;
		this.plcnam = plcnam;
		this.refgrpcod = refgrpcod;
		this.updgrpcod = updgrpcod;
		this.tmeznecod = tmeznecod;
		this.apporgcod = apporgcod;
		this.insymdhms = insymdhms;
		this.insnam = insnam;
		this.inskbn = inskbn;
		this.insmethodkbn = insmethodkbn;
		this.updeac = updeac;
		this.updymdhms = updymdhms;
		this.updnam = updnam;
		this.updkbn = updkbn;
		this.updmethodkbn = updmethodkbn;
	}

	// Property accessors

	public LmmmtrkevtId getId() {
		return this.id;
	}

	public void setId(LmmmtrkevtId id) {
		this.id = id;
	}

	public String getAboflg() {
		return this.aboflg;
	}

	public void setAboflg(String aboflg) {
		this.aboflg = aboflg;
	}

	public Long getRutodrnum() {
		return this.rutodrnum;
	}

	public void setRutodrnum(Long rutodrnum) {
		this.rutodrnum = rutodrnum;
	}

	public String getEvtkbn() {
		return this.evtkbn;
	}

	public void setEvtkbn(String evtkbn) {
		this.evtkbn = evtkbn;
	}

	public String getEvtnam() {
		return this.evtnam;
	}

	public void setEvtnam(String evtnam) {
		this.evtnam = evtnam;
	}

	public String getAltkbn() {
		return this.altkbn;
	}

	public void setAltkbn(String altkbn) {
		this.altkbn = altkbn;
	}

	public String getEvtmrgcod() {
		return this.evtmrgcod;
	}

	public void setEvtmrgcod(String evtmrgcod) {
		this.evtmrgcod = evtmrgcod;
	}

	public String getEvtmrgnam() {
		return this.evtmrgnam;
	}

	public void setEvtmrgnam(String evtmrgnam) {
		this.evtmrgnam = evtmrgnam;
	}


	public String getPlccod() {
		return this.plccod;
	}

	public void setPlccod(String plccod) {
		this.plccod = plccod;
	}

	public String getPlcnam() {
		return this.plcnam;
	}

	public void setPlcnam(String plcnam) {
		this.plcnam = plcnam;
	}

	public String getRefgrpcod() {
		return this.refgrpcod;
	}

	public void setRefgrpcod(String refgrpcod) {
		this.refgrpcod = refgrpcod;
	}

	public String getUpdgrpcod() {
		return this.updgrpcod;
	}

	public void setUpdgrpcod(String updgrpcod) {
		this.updgrpcod = updgrpcod;
	}

	public String getTmeznecod() {
		return this.tmeznecod;
	}

	public void setTmeznecod(String tmeznecod) {
		this.tmeznecod = tmeznecod;
	}

	public String getApporgcod() {
		return this.apporgcod;
	}

	public void setApporgcod(String apporgcod) {
		this.apporgcod = apporgcod;
	}

	public String getInsymdhms() {
		return this.insymdhms;
	}

	public void setInsymdhms(String insymdhms) {
		this.insymdhms = insymdhms;
	}

	public String getInsnam() {
		return this.insnam;
	}

	public void setInsnam(String insnam) {
		this.insnam = insnam;
	}

	public String getInskbn() {
		return this.inskbn;
	}

	public void setInskbn(String inskbn) {
		this.inskbn = inskbn;
	}

	public String getInsmethodkbn() {
		return this.insmethodkbn;
	}

	public void setInsmethodkbn(String insmethodkbn) {
		this.insmethodkbn = insmethodkbn;
	}

	public Long getUpdeac() {
		return this.updeac;
	}

	public void setUpdeac(Long updeac) {
		this.updeac = updeac;
	}

	public String getUpdymdhms() {
		return this.updymdhms;
	}

	public void setUpdymdhms(String updymdhms) {
		this.updymdhms = updymdhms;
	}

	public String getUpdnam() {
		return this.updnam;
	}

	public void setUpdnam(String updnam) {
		this.updnam = updnam;
	}

	public String getUpdkbn() {
		return this.updkbn;
	}

	public void setUpdkbn(String updkbn) {
		this.updkbn = updkbn;
	}

	public String getUpdmethodkbn() {
		return this.updmethodkbn;
	}

	public void setUpdmethodkbn(String updmethodkbn) {
		this.updmethodkbn = updmethodkbn;
	}

	public Long getStatrstme() {
		return statrstme;
	}

	public void setStatrstme(Long statrstme) {
		this.statrstme = statrstme;
	}

}