package org.cloud.model;

import java.util.Date;

/**
 * LmmmorgitmId generated by MyEclipse Persistence Tools
 */

@SuppressWarnings("serial")
public class LmmmorgitmId implements java.io.Serializable {

	// Fields

	private String tntcod;

	private String orgcod;

	private String orgitmcod;

	private Date appstaymdhms;

	// Constructors

	/** default constructor */
	public LmmmorgitmId() {
	}

	/** full constructor */
	public LmmmorgitmId(String tntcod, String orgcod, String orgitmcod,
			Date appstaymdhms) {
		this.tntcod = tntcod;
		this.orgcod = orgcod;
		this.orgitmcod = orgitmcod;
		this.appstaymdhms = appstaymdhms;
	}

	// Property accessors

	public String getTntcod() {
		return this.tntcod;
	}

	public void setTntcod(String tntcod) {
		this.tntcod = tntcod;
	}

	public String getOrgcod() {
		return this.orgcod;
	}

	public void setOrgcod(String orgcod) {
		this.orgcod = orgcod;
	}

	public String getOrgitmcod() {
		return this.orgitmcod;
	}

	public void setOrgitmcod(String orgitmcod) {
		this.orgitmcod = orgitmcod;
	}

	public Date getAppstaymdhms() {
		return this.appstaymdhms;
	}

	public void setAppstaymdhms(Date appstaymdhms) {
		this.appstaymdhms = appstaymdhms;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LmmmorgitmId))
			return false;
		LmmmorgitmId castOther = (LmmmorgitmId) other;

		return ((this.getTntcod() == castOther.getTntcod()) || (this
				.getTntcod() != null
				&& castOther.getTntcod() != null && this.getTntcod().equals(
				castOther.getTntcod())))
				&& ((this.getOrgcod() == castOther.getOrgcod()) || (this
						.getOrgcod() != null
						&& castOther.getOrgcod() != null && this.getOrgcod()
						.equals(castOther.getOrgcod())))
				&& ((this.getOrgitmcod() == castOther.getOrgitmcod()) || (this
						.getOrgitmcod() != null
						&& castOther.getOrgitmcod() != null && this
						.getOrgitmcod().equals(castOther.getOrgitmcod())))
				&& ((this.getAppstaymdhms() == castOther.getAppstaymdhms()) || (this
						.getAppstaymdhms() != null
						&& castOther.getAppstaymdhms() != null && this
						.getAppstaymdhms().equals(castOther.getAppstaymdhms())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTntcod() == null ? 0 : this.getTntcod().hashCode());
		result = 37 * result
				+ (getOrgcod() == null ? 0 : this.getOrgcod().hashCode());
		result = 37 * result
				+ (getOrgitmcod() == null ? 0 : this.getOrgitmcod().hashCode());
		result = 37
				* result
				+ (getAppstaymdhms() == null ? 0 : this.getAppstaymdhms()
						.hashCode());
		return result;
	}

}