package org.cloud.model;

/**
 * LmmmatrorgId generated by MyEclipse Persistence Tools
 */

public class LmmmatrorgId implements java.io.Serializable {

	// Fields

	private String tntcod;

	private String atrgrpcod;

	private String orgcod;

	// Constructors

	/** default constructor */
	public LmmmatrorgId() {
	}

	/** full constructor */
	public LmmmatrorgId(String tntcod, String atrgrpcod, String orgcod) {
		this.tntcod = tntcod;
		this.atrgrpcod = atrgrpcod;
		this.orgcod = orgcod;
	}

	// Property accessors

	public String getTntcod() {
		return this.tntcod;
	}

	public void setTntcod(String tntcod) {
		this.tntcod = tntcod;
	}

	public String getAtrgrpcod() {
		return this.atrgrpcod;
	}

	public void setAtrgrpcod(String atrgrpcod) {
		this.atrgrpcod = atrgrpcod;
	}

	public String getOrgcod() {
		return this.orgcod;
	}

	public void setOrgcod(String orgcod) {
		this.orgcod = orgcod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LmmmatrorgId))
			return false;
		LmmmatrorgId castOther = (LmmmatrorgId) other;

		return ((this.getTntcod() == castOther.getTntcod()) || (this
				.getTntcod() != null
				&& castOther.getTntcod() != null && this.getTntcod().equals(
				castOther.getTntcod())))
				&& ((this.getAtrgrpcod() == castOther.getAtrgrpcod()) || (this
						.getAtrgrpcod() != null
						&& castOther.getAtrgrpcod() != null && this
						.getAtrgrpcod().equals(castOther.getAtrgrpcod())))
				&& ((this.getOrgcod() == castOther.getOrgcod()) || (this
						.getOrgcod() != null
						&& castOther.getOrgcod() != null && this.getOrgcod()
						.equals(castOther.getOrgcod())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTntcod() == null ? 0 : this.getTntcod().hashCode());
		result = 37 * result
				+ (getAtrgrpcod() == null ? 0 : this.getAtrgrpcod().hashCode());
		result = 37 * result
				+ (getOrgcod() == null ? 0 : this.getOrgcod().hashCode());
		return result;
	}

}