package org.cloud.model;

import java.util.Date;

/**
 * Lmmmgrl generated by MyEclipse Persistence Tools
 */

public class Lmmmgrl implements java.io.Serializable {

	// Fields

	private LmmmgrlId id;
	
	private Lmmmorg id1;
	
	private String tntcod;

	private String gnrprpkbn;

	private String gnrprpcod;
	
	private String aboflg;

	private String codoutcod;

	private String gnrprpnam1;

	private String gnrprpnam2;

	private String apporgcod;

	private Date insymdhms;

	private String insnam;

	private String inskbn;

	private String insmethodkbn;

	private Long updeac;

	private Date updymdhms;

	private String updnam;

	private String updkbn;

	private String updmethodkbn;
	
	private Long updeac1;
	
	private String orgnam1;
	public Lmmmorg getId1() {
		return id1;
	}

	public void setId1(Lmmmorg id1) {
		this.id1 = id1;
	}
	
	

	// Constructors

	public String getOrgnam1() {
		return orgnam1;
	}

	public void setOrgnam1(String orgnam1) {
		this.orgnam1 = orgnam1;
	}

	public Long getUpdeac1() {
		return updeac1;
	}

	public void setUpdeac1(Long updeac1) {
		this.updeac1 = updeac1;
	}

	/** default constructor */
	public Lmmmgrl() {
	}

	/** minimal constructor */
	public Lmmmgrl(LmmmgrlId id) {
		this.id = id;
	}

	/** full constructor */
	public Lmmmgrl(LmmmgrlId id, String aboflg, String codoutcod,
			String gnrprpnam1, String gnrprpnam2, String apporgcod,
			Date insymdhms, String insnam, String inskbn,
			String insmethodkbn, Long updeac, Date updymdhms, String updnam,
			String updkbn, String updmethodkbn) {
		this.id = id;
		this.aboflg = aboflg;
		this.codoutcod = codoutcod;
		this.gnrprpnam1 = gnrprpnam1;
		this.gnrprpnam2 = gnrprpnam2;
		this.apporgcod = apporgcod;
		this.insymdhms = insymdhms;
		this.insnam = insnam;
		this.inskbn = inskbn;
		this.insmethodkbn = insmethodkbn;
		this.updeac = updeac;
		this.updymdhms = updymdhms;
		this.updnam = updnam;
		this.updkbn = updkbn;
		this.updmethodkbn = updmethodkbn;
	}

	// Property accessors

	public LmmmgrlId getId() {
		return this.id;
	}

	public void setId(LmmmgrlId id) {
		this.id = id;
	}

	public String getAboflg() {
		return this.aboflg;
	}

	public void setAboflg(String aboflg) {
		this.aboflg = aboflg;
	}

	public String getCodoutcod() {
		return this.codoutcod;
	}

	public void setCodoutcod(String codoutcod) {
		this.codoutcod = codoutcod;
	}

	public String getGnrprpnam1() {
		return this.gnrprpnam1;
	}

	public void setGnrprpnam1(String gnrprpnam1) {
		this.gnrprpnam1 = gnrprpnam1;
	}

	public String getGnrprpnam2() {
		return this.gnrprpnam2;
	}

	public void setGnrprpnam2(String gnrprpnam2) {
		this.gnrprpnam2 = gnrprpnam2;
	}

	public String getApporgcod() {
		return this.apporgcod;
	}

	public void setApporgcod(String apporgcod) {
		this.apporgcod = apporgcod;
	}

	public Date getInsymdhms() {
		return this.insymdhms;
	}

	public void setInsymdhms(Date insymdhms) {
		this.insymdhms = insymdhms;
	}

	public String getInsnam() {
		return this.insnam;
	}

	public void setInsnam(String insnam) {
		this.insnam = insnam;
	}

	public String getInskbn() {
		return this.inskbn;
	}

	public void setInskbn(String inskbn) {
		this.inskbn = inskbn;
	}

	public String getInsmethodkbn() {
		return this.insmethodkbn;
	}

	public void setInsmethodkbn(String insmethodkbn) {
		this.insmethodkbn = insmethodkbn;
	}

	public Long getUpdeac() {
		return this.updeac;
	}

	public void setUpdeac(Long updeac) {
		this.updeac = updeac;
	}

	public Date getUpdymdhms() {
		return this.updymdhms;
	}

	public void setUpdymdhms(Date updymdhms) {
		this.updymdhms = updymdhms;
	}

	public String getUpdnam() {
		return this.updnam;
	}

	public void setUpdnam(String updnam) {
		this.updnam = updnam;
	}

	public String getUpdkbn() {
		return this.updkbn;
	}

	public void setUpdkbn(String updkbn) {
		this.updkbn = updkbn;
	}

	public String getUpdmethodkbn() {
		return this.updmethodkbn;
	}

	public void setUpdmethodkbn(String updmethodkbn) {
		this.updmethodkbn = updmethodkbn;
	}

	/**
	 * @return the tntcod
	 */
	public String getTntcod() {
		return tntcod;
	}

	/**
	 * @param tntcod the tntcod to set
	 */
	public void setTntcod(String tntcod) {
		this.tntcod = tntcod;
	}

	/**
	 * @return the gnrprpkbn
	 */
	public String getGnrprpkbn() {
		return gnrprpkbn;
	}

	/**
	 * @param gnrprpkbn the gnrprpkbn to set
	 */
	public void setGnrprpkbn(String gnrprpkbn) {
		this.gnrprpkbn = gnrprpkbn;
	}

	/**
	 * @return the gnrprpcod
	 */
	public String getGnrprpcod() {
		return gnrprpcod;
	}

	/**
	 * @param gnrprpcod the gnrprpcod to set
	 */
	public void setGnrprpcod(String gnrprpcod) {
		this.gnrprpcod = gnrprpcod;
	}

}