package org.cloud.model;

/**
 * LmmmtrkarvdptId generated by MyEclipse Persistence Tools
 */

public class LmmmtrkarvdptId implements java.io.Serializable {

	// Fields

	private String tntcod;

	private String sipplccod;

	private String fnlplccod;

	// Constructors

	/** default constructor */
	public LmmmtrkarvdptId() {
	}

	/** full constructor */
	public LmmmtrkarvdptId(String tntcod, String sipplccod, String fnlplccod) {
		this.tntcod = tntcod;
		this.sipplccod = sipplccod;
		this.fnlplccod = fnlplccod;
	}

	// Property accessors

	public String getTntcod() {
		return this.tntcod;
	}

	public void setTntcod(String tntcod) {
		this.tntcod = tntcod;
	}

	public String getSipplccod() {
		return this.sipplccod;
	}

	public void setSipplccod(String sipplccod) {
		this.sipplccod = sipplccod;
	}

	public String getFnlplccod() {
		return this.fnlplccod;
	}

	public void setFnlplccod(String fnlplccod) {
		this.fnlplccod = fnlplccod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LmmmtrkarvdptId))
			return false;
		LmmmtrkarvdptId castOther = (LmmmtrkarvdptId) other;

		return ((this.getTntcod() == castOther.getTntcod()) || (this
				.getTntcod() != null
				&& castOther.getTntcod() != null && this.getTntcod().equals(
				castOther.getTntcod())))
				&& ((this.getSipplccod() == castOther.getSipplccod()) || (this
						.getSipplccod() != null
						&& castOther.getSipplccod() != null && this
						.getSipplccod().equals(castOther.getSipplccod())))
				&& ((this.getFnlplccod() == castOther.getFnlplccod()) || (this
						.getFnlplccod() != null
						&& castOther.getFnlplccod() != null && this
						.getFnlplccod().equals(castOther.getFnlplccod())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTntcod() == null ? 0 : this.getTntcod().hashCode());
		result = 37 * result
				+ (getSipplccod() == null ? 0 : this.getSipplccod().hashCode());
		result = 37 * result
				+ (getFnlplccod() == null ? 0 : this.getFnlplccod().hashCode());
		return result;
	}

}