package org.cloud.model;

/**
 * LmmmgrlId generated by MyEclipse Persistence Tools
 */

public class LmmmgrlId implements java.io.Serializable {

	// Fields

	private String tntcod;

	private String gnrprpkbn;

	private String gnrprpcod;

	// Constructors

	/** default constructor */
	public LmmmgrlId() {
	}

	/** full constructor */
	public LmmmgrlId(String tntcod, String gnrprpkbn, String gnrprpcod) {
		this.tntcod = tntcod;
		this.gnrprpkbn = gnrprpkbn;
		this.gnrprpcod = gnrprpcod;
	}

	// Property accessors

	public String getTntcod() {
		return this.tntcod;
	}

	public void setTntcod(String tntcod) {
		this.tntcod = tntcod;
	}

	public String getGnrprpkbn() {
		return this.gnrprpkbn;
	}

	public void setGnrprpkbn(String gnrprpkbn) {
		this.gnrprpkbn = gnrprpkbn;
	}

	public String getGnrprpcod() {
		return this.gnrprpcod;
	}

	public void setGnrprpcod(String gnrprpcod) {
		this.gnrprpcod = gnrprpcod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LmmmgrlId))
			return false;
		LmmmgrlId castOther = (LmmmgrlId) other;

		return ((this.getTntcod() == castOther.getTntcod()) || (this
				.getTntcod() != null
				&& castOther.getTntcod() != null && this.getTntcod().equals(
				castOther.getTntcod())))
				&& ((this.getGnrprpkbn() == castOther.getGnrprpkbn()) || (this
						.getGnrprpkbn() != null
						&& castOther.getGnrprpkbn() != null && this
						.getGnrprpkbn().equals(castOther.getGnrprpkbn())))
				&& ((this.getGnrprpcod() == castOther.getGnrprpcod()) || (this
						.getGnrprpcod() != null
						&& castOther.getGnrprpcod() != null && this
						.getGnrprpcod().equals(castOther.getGnrprpcod())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTntcod() == null ? 0 : this.getTntcod().hashCode());
		result = 37 * result
				+ (getGnrprpkbn() == null ? 0 : this.getGnrprpkbn().hashCode());
		result = 37 * result
				+ (getGnrprpcod() == null ? 0 : this.getGnrprpcod().hashCode());
		return result;
	}

}