package org.cloud.model;

import java.util.Date;

/**
 * Lmmmplc generated by MyEclipse Persistence Tools
 */

public class Lmmmplc implements java.io.Serializable {


	private static final long serialVersionUID = 8493076929039880812L;

	private String tntcod;
	
	private String plccod;
	
	private String conam;
	
	private Long updeac1;
	
	
	
	public Long getUpdeac1() {
		return updeac1;
	}

	public void setUpdeac1(Long updeac12) {
		this.updeac1 = updeac12;
	}

	public String getConam() {
		return conam;
	}

	public void setConam(String conam) {
		this.conam = conam;
	}

	public String getPlccod() {
		return plccod;
	}

	public void setPlccod(String plccod) {
		this.plccod = plccod;
	}

	public String getTntcod() {
		return tntcod;
	}

	public void setTntcod(String tntcod) {
		this.tntcod = tntcod;
	}

	private LmmmplcId id;

	private String aboflg;

	private String plcnam;

	private String adrnam1;

	private String adrnam2;

	private String adrnam3;

	private String adrnam4;

	private String zipcod;

	private String ctrcod;

	private String tmeznecod;

	private String apporgcod;

	private Date insymdhms;

	private String insnam;

	private String inskbn;

	private String insmethodkbn;

	private Long updeac;

	private Date updymdhms;

	private String updnam;

	private String updkbn;

	private String updmethodkbn;

	// Constructors

	/** default constructor */
	public Lmmmplc() {
	}

	/** minimal constructor */
	public Lmmmplc(LmmmplcId id) {
		this.id = id;
	}

	/** full constructor */
	public Lmmmplc(LmmmplcId id, String aboflg, String plcnam, String adrnam1,
			String adrnam2, String adrnam3, String adrnam4, String zipcod,
			String ctrcod, String tmeznecod, String apporgcod,
			Date insymdhms, String insnam, String inskbn,
			String insmethodkbn, Long updeac, Date updymdhms, String updnam,
			String updkbn, String updmethodkbn) {
		this.id = id;
		this.aboflg = aboflg;
		this.plcnam = plcnam;
		this.adrnam1 = adrnam1;
		this.adrnam2 = adrnam2;
		this.adrnam3 = adrnam3;
		this.adrnam4 = adrnam4;
		this.zipcod = zipcod;
		this.ctrcod = ctrcod;
		this.tmeznecod = tmeznecod;
		this.apporgcod = apporgcod;
		this.insymdhms = insymdhms;
		this.insnam = insnam;
		this.inskbn = inskbn;
		this.insmethodkbn = insmethodkbn;
		this.updeac = updeac;
		this.updymdhms = updymdhms;
		this.updnam = updnam;
		this.updkbn = updkbn;
		this.updmethodkbn = updmethodkbn;
	}

	// Property accessors

	public LmmmplcId getId() {
		return this.id;
	}

	public void setId(LmmmplcId id) {
		this.id = id;
	}

	public String getAboflg() {
		return this.aboflg;
	}

	public void setAboflg(String aboflg) {
		this.aboflg = aboflg;
	}

	public String getPlcnam() {
		return this.plcnam;
	}

	public void setPlcnam(String plcnam) {
		this.plcnam = plcnam;
	}

	public String getAdrnam1() {
		return this.adrnam1;
	}

	public void setAdrnam1(String adrnam1) {
		this.adrnam1 = adrnam1;
	}

	public String getAdrnam2() {
		return this.adrnam2;
	}

	public void setAdrnam2(String adrnam2) {
		this.adrnam2 = adrnam2;
	}

	public String getAdrnam3() {
		return this.adrnam3;
	}

	public void setAdrnam3(String adrnam3) {
		this.adrnam3 = adrnam3;
	}

	public String getAdrnam4() {
		return this.adrnam4;
	}

	public void setAdrnam4(String adrnam4) {
		this.adrnam4 = adrnam4;
	}

	public String getZipcod() {
		return this.zipcod;
	}

	public void setZipcod(String zipcod) {
		this.zipcod = zipcod;
	}

	public String getCtrcod() {
		return this.ctrcod;
	}

	public void setCtrcod(String ctrcod) {
		this.ctrcod = ctrcod;
	}

	public String getTmeznecod() {
		return this.tmeznecod;
	}

	public void setTmeznecod(String tmeznecod) {
		this.tmeznecod = tmeznecod;
	}

	public String getApporgcod() {
		return this.apporgcod;
	}

	public void setApporgcod(String apporgcod) {
		this.apporgcod = apporgcod;
	}

	public Date getInsymdhms() {
		return this.insymdhms;
	}

	public void setInsymdhms(Date date) {
		this.insymdhms = date;
	}

	public String getInsnam() {
		return this.insnam;
	}

	public void setInsnam(String insnam) {
		this.insnam = insnam;
	}

	public String getInskbn() {
		return this.inskbn;
	}

	public void setInskbn(String inskbn) {
		this.inskbn = inskbn;
	}

	public String getInsmethodkbn() {
		return this.insmethodkbn;
	}

	public void setInsmethodkbn(String insmethodkbn) {
		this.insmethodkbn = insmethodkbn;
	}

	public Long getUpdeac() {
		return this.updeac;
	}

	public void setUpdeac(Long updeac) {
		this.updeac = updeac;
	}

	public Date getUpdymdhms() {
		return this.updymdhms;
	}

	public void setUpdymdhms(Date updymdhms) {
		this.updymdhms = updymdhms;
	}

	public String getUpdnam() {
		return this.updnam;
	}

	public void setUpdnam(String updnam) {
		this.updnam = updnam;
	}

	public String getUpdkbn() {
		return this.updkbn;
	}

	public void setUpdkbn(String updkbn) {
		this.updkbn = updkbn;
	}

	public String getUpdmethodkbn() {
		return this.updmethodkbn;
	}

	public void setUpdmethodkbn(String updmethodkbn) {
		this.updmethodkbn = updmethodkbn;
	}

}