package org.cloud.model;

/**
 * Lmmmtrkg generated by MyEclipse Persistence Tools
 */

public class Lmmmtrkg2 implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private String tntcod;//テナントコード
	
	private String aboflg;//マークを廃止する

	private String trkgrpnam;//保護者追跡コード

	private String trkgrpcod;//家长跟踪编码
	
	private String orgcod;//組織テーブルは、コードの内容値をapporgcodに一致させるように構成する
	
	public String orgnam1;//検索コンテンツを表示する
	
	private String apporgcod;//申请组织代码

	private String insymdhms;//ログイン日時分秒

	private String insnam;//登録者

	private String inskbn;//登録者区分

	private String insmethodkbn;//登録方法の区分

	private Long updeac;//回数を更新する

	private String updymdhms;//年月日を更新した時は秒を切る

	private String updnam;//更新者

	private String updkbn;//更新者区分

	private String updmethodkbn;//更新方法の使い分け

	public String getTntcod() {
		return tntcod;
	}

	public void setTntcod(String tntcod) {
		this.tntcod = tntcod;
	}

	public String getAboflg() {
		return aboflg;
	}

	public void setAboflg(String aboflg) {
		this.aboflg = aboflg;
	}

	public String getTrkgrpnam() {
		return trkgrpnam;
	}

	public void setTrkgrpnam(String trkgrpnam) {
		this.trkgrpnam = trkgrpnam;
	}

	public String getTrkgrpcod() {
		return trkgrpcod;
	}

	public void setTrkgrpcod(String trkgrpcod) {
		this.trkgrpcod = trkgrpcod;
	}

	public String getOrgcod() {
		return orgcod;
	}

	public void setOrgcod(String orgcod) {
		this.orgcod = orgcod;
	}

	public String getOrgnam1() {
		return orgnam1;
	}

	public void setOrgnam1(String orgnam1) {
		this.orgnam1 = orgnam1;
	}

	public String getApporgcod() {
		return apporgcod;
	}

	public void setApporgcod(String apporgcod) {
		this.apporgcod = apporgcod;
	}

	public String getInsymdhms() {
		return insymdhms;
	}

	public void setInsymdhms(String insymdhms) {
		this.insymdhms = insymdhms;
	}

	public String getInsnam() {
		return insnam;
	}

	public void setInsnam(String insnam) {
		this.insnam = insnam;
	}

	public String getInskbn() {
		return inskbn;
	}

	public void setInskbn(String inskbn) {
		this.inskbn = inskbn;
	}

	public String getInsmethodkbn() {
		return insmethodkbn;
	}

	public void setInsmethodkbn(String insmethodkbn) {
		this.insmethodkbn = insmethodkbn;
	}

	public Long getUpdeac() {
		return updeac;
	}

	public void setUpdeac(Long updeac) {
		this.updeac = updeac;
	}

	public String getUpdymdhms() {
		return updymdhms;
	}

	public void setUpdymdhms(String updymdhms) {
		this.updymdhms = updymdhms;
	}

	public String getUpdnam() {
		return updnam;
	}

	public void setUpdnam(String updnam) {
		this.updnam = updnam;
	}

	public String getUpdkbn() {
		return updkbn;
	}

	public void setUpdkbn(String updkbn) {
		this.updkbn = updkbn;
	}

	public String getUpdmethodkbn() {
		return updmethodkbn;
	}

	public void setUpdmethodkbn(String updmethodkbn) {
		this.updmethodkbn = updmethodkbn;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((aboflg == null) ? 0 : aboflg.hashCode());
		result = prime * result + ((apporgcod == null) ? 0 : apporgcod.hashCode());
		result = prime * result + ((inskbn == null) ? 0 : inskbn.hashCode());
		result = prime * result + ((insmethodkbn == null) ? 0 : insmethodkbn.hashCode());
		result = prime * result + ((insnam == null) ? 0 : insnam.hashCode());
		result = prime * result + ((insymdhms == null) ? 0 : insymdhms.hashCode());
		result = prime * result + ((orgcod == null) ? 0 : orgcod.hashCode());
		result = prime * result + ((orgnam1 == null) ? 0 : orgnam1.hashCode());
		result = prime * result + ((tntcod == null) ? 0 : tntcod.hashCode());
		result = prime * result + ((trkgrpcod == null) ? 0 : trkgrpcod.hashCode());
		result = prime * result + ((trkgrpnam == null) ? 0 : trkgrpnam.hashCode());
		result = prime * result + ((updeac == null) ? 0 : updeac.hashCode());
		result = prime * result + ((updkbn == null) ? 0 : updkbn.hashCode());
		result = prime * result + ((updmethodkbn == null) ? 0 : updmethodkbn.hashCode());
		result = prime * result + ((updnam == null) ? 0 : updnam.hashCode());
		result = prime * result + ((updymdhms == null) ? 0 : updymdhms.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Lmmmtrkg2 other = (Lmmmtrkg2) obj;
		if (aboflg == null) {
			if (other.aboflg != null)
				return false;
		} else if (!aboflg.equals(other.aboflg))
			return false;
		if (apporgcod == null) {
			if (other.apporgcod != null)
				return false;
		} else if (!apporgcod.equals(other.apporgcod))
			return false;
		if (inskbn == null) {
			if (other.inskbn != null)
				return false;
		} else if (!inskbn.equals(other.inskbn))
			return false;
		if (insmethodkbn == null) {
			if (other.insmethodkbn != null)
				return false;
		} else if (!insmethodkbn.equals(other.insmethodkbn))
			return false;
		if (insnam == null) {
			if (other.insnam != null)
				return false;
		} else if (!insnam.equals(other.insnam))
			return false;
		if (insymdhms == null) {
			if (other.insymdhms != null)
				return false;
		} else if (!insymdhms.equals(other.insymdhms))
			return false;
		if (orgcod == null) {
			if (other.orgcod != null)
				return false;
		} else if (!orgcod.equals(other.orgcod))
			return false;
		if (orgnam1 == null) {
			if (other.orgnam1 != null)
				return false;
		} else if (!orgnam1.equals(other.orgnam1))
			return false;
		if (tntcod == null) {
			if (other.tntcod != null)
				return false;
		} else if (!tntcod.equals(other.tntcod))
			return false;
		if (trkgrpcod == null) {
			if (other.trkgrpcod != null)
				return false;
		} else if (!trkgrpcod.equals(other.trkgrpcod))
			return false;
		if (trkgrpnam == null) {
			if (other.trkgrpnam != null)
				return false;
		} else if (!trkgrpnam.equals(other.trkgrpnam))
			return false;
		if (updeac == null) {
			if (other.updeac != null)
				return false;
		} else if (!updeac.equals(other.updeac))
			return false;
		if (updkbn == null) {
			if (other.updkbn != null)
				return false;
		} else if (!updkbn.equals(other.updkbn))
			return false;
		if (updmethodkbn == null) {
			if (other.updmethodkbn != null)
				return false;
		} else if (!updmethodkbn.equals(other.updmethodkbn))
			return false;
		if (updnam == null) {
			if (other.updnam != null)
				return false;
		} else if (!updnam.equals(other.updnam))
			return false;
		if (updymdhms == null) {
			if (other.updymdhms != null)
				return false;
		} else if (!updymdhms.equals(other.updymdhms))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Lmmmtrkg2 [tntcod=" + tntcod + ", aboflg=" + aboflg + ", trkgrpnam=" + trkgrpnam + ", trkgrpcod="
				+ trkgrpcod + ", orgcod=" + orgcod + ", orgnam1=" + orgnam1 + ", apporgcod=" + apporgcod
				+ ", insymdhms=" + insymdhms + ", insnam=" + insnam + ", inskbn=" + inskbn + ", insmethodkbn="
				+ insmethodkbn + ", updeac=" + updeac + ", updymdhms=" + updymdhms + ", updnam=" + updnam + ", updkbn="
				+ updkbn + ", updmethodkbn=" + updmethodkbn + "]";
	}

	public Lmmmtrkg2(String tntcod, String aboflg, String trkgrpnam, String trkgrpcod, String orgcod, String orgnam1,
			String apporgcod, String insymdhms, String insnam, String inskbn, String insmethodkbn, Long updeac,
			String updymdhms, String updnam, String updkbn, String updmethodkbn) {
		super();
		this.tntcod = tntcod;
		this.aboflg = aboflg;
		this.trkgrpnam = trkgrpnam;
		this.trkgrpcod = trkgrpcod;
		this.orgcod = orgcod;
		this.orgnam1 = orgnam1;
		this.apporgcod = apporgcod;
		this.insymdhms = insymdhms;
		this.insnam = insnam;
		this.inskbn = inskbn;
		this.insmethodkbn = insmethodkbn;
		this.updeac = updeac;
		this.updymdhms = updymdhms;
		this.updnam = updnam;
		this.updkbn = updkbn;
		this.updmethodkbn = updmethodkbn;
	}

	public Lmmmtrkg2() {
		super();
		// TODO Auto-generated constructor stub
	}

	

}