package org.cloud.model;

import java.util.Date;

/**
 * Lmmmevt generated by MyEclipse Persistence Tools
 */

public class Lmmmevt implements java.io.Serializable {

	/**
	 *serialVersionUID
	 *2012/03/08
	 */
	private static final long serialVersionUID = 1L;

	// Fields

	private LmmmevtId id;

	private String aboflg;

	private String evtnam;

	private String atnfil;

	private String evtkbn01;

	private String evtkbn02;

	private String evtkbn03;

	private String evtkbn04;

	private String evtkbn05;

	private String evtkbn06;

	private String evtkbn07;

	private String evtkbn08;

	private String evtkbn09;

	private String evtkbn10;

	private String evtkbn11;

	private String evtkbn12;

	private String evtkbn13;

	private String evtkbn14;

	private String evtkbn15;

	private String evtkbn16;

	private String evtkbn17;

	private String evtkbn18;

	private String evtkbn19;

	private String evtkbn20;

	private String apporgcod;

	private Date insymdhms;

	private String insnam;

	private String inskbn;

	private String insmethodkbn;

	private Long updeac;

	private Date updymdhms;

	private String updnam;

	private String updkbn;

	private String updmethodkbn;
   
	private String evtcod;
	
	private String tntcod;
	
	private String gnrprpcod;
	// Constructors

	/** default constructor */
	public Lmmmevt() {
	}

	/** minimal constructor */
	public Lmmmevt(LmmmevtId id) {
		this.id = id;
	}

	/** full constructor */
	public Lmmmevt(LmmmevtId id, String aboflg, String evtnam, String atnfil,
			String evtkbn01, String evtkbn02, String evtkbn03, String evtkbn04,
			String evtkbn05, String evtkbn06, String evtkbn07, String evtkbn08,
			String evtkbn09, String evtkbn10, String evtkbn11, String evtkbn12,
			String evtkbn13, String evtkbn14, String evtkbn15, String evtkbn16,
			String evtkbn17, String evtkbn18, String evtkbn19, String evtkbn20,
			String apporgcod, Date insymdhms, String insnam, String inskbn,
			String insmethodkbn, Long updeac, Date updymdhms, String updnam,
			String updkbn, String updmethodkbn,String tntcod,String gnrprpcod) {
		this.id = id;
		this.aboflg = aboflg;
		this.evtnam = evtnam;
		this.atnfil = atnfil;
		this.evtkbn01 = evtkbn01;
		this.evtkbn02 = evtkbn02;
		this.evtkbn03 = evtkbn03;
		this.evtkbn04 = evtkbn04;
		this.evtkbn05 = evtkbn05;
		this.evtkbn06 = evtkbn06;
		this.evtkbn07 = evtkbn07;
		this.evtkbn08 = evtkbn08;
		this.evtkbn09 = evtkbn09;
		this.evtkbn10 = evtkbn10;
		this.evtkbn11 = evtkbn11;
		this.evtkbn12 = evtkbn12;
		this.evtkbn13 = evtkbn13;
		this.evtkbn14 = evtkbn14;
		this.evtkbn15 = evtkbn15;
		this.evtkbn16 = evtkbn16;
		this.evtkbn17 = evtkbn17;
		this.evtkbn18 = evtkbn18;
		this.evtkbn19 = evtkbn19;
		this.evtkbn20 = evtkbn20;
		this.apporgcod = apporgcod;
		this.insymdhms = insymdhms;
		this.insnam = insnam;
		this.inskbn = inskbn;
		this.insmethodkbn = insmethodkbn;
		this.updeac = updeac;
		this.updymdhms = updymdhms;
		this.updnam = updnam;
		this.updkbn = updkbn;
		this.updmethodkbn = updmethodkbn;
		this.tntcod = tntcod;
		this.gnrprpcod = gnrprpcod;
	}

	public LmmmevtId getId() {
		return id;
	}

	public void setId(LmmmevtId id) {
		this.id = id;
	}

	public String getAboflg() {
		return aboflg;
	}

	public void setAboflg(String aboflg) {
		this.aboflg = aboflg;
	}

	public String getEvtnam() {
		return evtnam;
	}

	public void setEvtnam(String evtnam) {
		this.evtnam = evtnam;
	}

	public String getAtnfil() {
		return atnfil;
	}

	public void setAtnfil(String atnfil) {
		this.atnfil = atnfil;
	}

	public String getEvtkbn01() {
		return evtkbn01;
	}

	public void setEvtkbn01(String evtkbn01) {
		this.evtkbn01 = evtkbn01;
	}

	public String getEvtkbn02() {
		return evtkbn02;
	}

	public void setEvtkbn02(String evtkbn02) {
		this.evtkbn02 = evtkbn02;
	}

	public String getEvtkbn03() {
		return evtkbn03;
	}

	public void setEvtkbn03(String evtkbn03) {
		this.evtkbn03 = evtkbn03;
	}

	public String getEvtkbn04() {
		return evtkbn04;
	}

	public void setEvtkbn04(String evtkbn04) {
		this.evtkbn04 = evtkbn04;
	}

	public String getEvtkbn05() {
		return evtkbn05;
	}

	public void setEvtkbn05(String evtkbn05) {
		this.evtkbn05 = evtkbn05;
	}

	public String getEvtkbn06() {
		return evtkbn06;
	}

	public void setEvtkbn06(String evtkbn06) {
		this.evtkbn06 = evtkbn06;
	}

	public String getEvtkbn07() {
		return evtkbn07;
	}

	public void setEvtkbn07(String evtkbn07) {
		this.evtkbn07 = evtkbn07;
	}

	public String getEvtkbn08() {
		return evtkbn08;
	}

	public void setEvtkbn08(String evtkbn08) {
		this.evtkbn08 = evtkbn08;
	}

	public String getEvtkbn09() {
		return evtkbn09;
	}

	public void setEvtkbn09(String evtkbn09) {
		this.evtkbn09 = evtkbn09;
	}

	public String getEvtkbn10() {
		return evtkbn10;
	}

	public void setEvtkbn10(String evtkbn10) {
		this.evtkbn10 = evtkbn10;
	}

	public String getEvtkbn11() {
		return evtkbn11;
	}

	public void setEvtkbn11(String evtkbn11) {
		this.evtkbn11 = evtkbn11;
	}

	public String getEvtkbn12() {
		return evtkbn12;
	}

	public void setEvtkbn12(String evtkbn12) {
		this.evtkbn12 = evtkbn12;
	}

	public String getEvtkbn13() {
		return evtkbn13;
	}

	public void setEvtkbn13(String evtkbn13) {
		this.evtkbn13 = evtkbn13;
	}

	public String getEvtkbn14() {
		return evtkbn14;
	}

	public void setEvtkbn14(String evtkbn14) {
		this.evtkbn14 = evtkbn14;
	}

	public String getEvtkbn15() {
		return evtkbn15;
	}

	public void setEvtkbn15(String evtkbn15) {
		this.evtkbn15 = evtkbn15;
	}

	public String getEvtkbn16() {
		return evtkbn16;
	}

	public void setEvtkbn16(String evtkbn16) {
		this.evtkbn16 = evtkbn16;
	}

	public String getEvtkbn17() {
		return evtkbn17;
	}

	public void setEvtkbn17(String evtkbn17) {
		this.evtkbn17 = evtkbn17;
	}

	public String getEvtkbn18() {
		return evtkbn18;
	}

	public void setEvtkbn18(String evtkbn18) {
		this.evtkbn18 = evtkbn18;
	}

	public String getEvtkbn19() {
		return evtkbn19;
	}

	public void setEvtkbn19(String evtkbn19) {
		this.evtkbn19 = evtkbn19;
	}

	public String getEvtkbn20() {
		return evtkbn20;
	}

	public void setEvtkbn20(String evtkbn20) {
		this.evtkbn20 = evtkbn20;
	}

	public String getApporgcod() {
		return apporgcod;
	}

	public void setApporgcod(String apporgcod) {
		this.apporgcod = apporgcod;
	}

	public Date getInsymdhms() {
		return insymdhms;
	}

	public void setInsymdhms(Date insymdhms) {
		this.insymdhms = insymdhms;
	}

	public String getInsnam() {
		return insnam;
	}

	public void setInsnam(String insnam) {
		this.insnam = insnam;
	}

	public String getInskbn() {
		return inskbn;
	}

	public void setInskbn(String inskbn) {
		this.inskbn = inskbn;
	}

	public String getInsmethodkbn() {
		return insmethodkbn;
	}

	public void setInsmethodkbn(String insmethodkbn) {
		this.insmethodkbn = insmethodkbn;
	}

	public Long getUpdeac() {
		return updeac;
	}

	public void setUpdeac(Long updeac) {
		this.updeac = updeac;
	}

	public Date getUpdymdhms() {
		return updymdhms;
	}

	public void setUpdymdhms(Date updymdhms) {
		this.updymdhms = updymdhms;
	}

	public String getUpdnam() {
		return updnam;
	}

	public void setUpdnam(String updnam) {
		this.updnam = updnam;
	}

	public String getUpdkbn() {
		return updkbn;
	}

	public void setUpdkbn(String updkbn) {
		this.updkbn = updkbn;
	}

	public String getUpdmethodkbn() {
		return updmethodkbn;
	}

	public void setUpdmethodkbn(String updmethodkbn) {
		this.updmethodkbn = updmethodkbn;
	}

	public String getEvtcod() {
		return evtcod;
	}

	public void setEvtcod(String evtcod) {
		this.evtcod = evtcod;
	}

	public String getTntcod() {
		return tntcod;
	}

	public void setTntcod(String tntcod) {
		this.tntcod = tntcod;
	}

	public String getGnrprpcod() {
		return gnrprpcod;
	}

	public void setGnrprpcod(String gnrprpcod) {
		this.gnrprpcod = gnrprpcod;
	}

	public static long getSerialVersionUID() {
		return serialVersionUID;
	}

	// Property accessors

	/*public LmmmevtId getId() {
		return this.id;
	}

	public void setId(LmmmevtId id) {
		this.id = id;
	}

	public String getEvtnam() {
		return this.evtnam;
	}

	public void setEvtnam(String evtnam) {
		this.evtnam = evtnam;
	}

	public String getAtnfil() {
		return this.atnfil;
	}

	public void setAtnfil(String atnfil) {
		this.atnfil = atnfil;
	}

	public String getEvtkbn01() {
		return this.evtkbn01;
	}

	public void setEvtkbn01(String evtkbn01) {
		this.evtkbn01 = evtkbn01;
	}

	public String getEvtkbn02() {
		return this.evtkbn02;
	}

	public void setEvtkbn02(String evtkbn02) {
		this.evtkbn02 = evtkbn02;
	}

	public String getEvtkbn03() {
		return this.evtkbn03;
	}

	public void setEvtkbn03(String evtkbn03) {
		this.evtkbn03 = evtkbn03;
	}

	public String getEvtkbn04() {
		return this.evtkbn04;
	}

	public void setEvtkbn04(String evtkbn04) {
		this.evtkbn04 = evtkbn04;
	}

	public String getEvtkbn05() {
		return this.evtkbn05;
	}

	public void setEvtkbn05(String evtkbn05) {
		this.evtkbn05 = evtkbn05;
	}

	public String getEvtkbn06() {
		return this.evtkbn06;
	}

	public void setEvtkbn06(String evtkbn06) {
		this.evtkbn06 = evtkbn06;
	}

	public String getEvtkbn07() {
		return this.evtkbn07;
	}

	public void setEvtkbn07(String evtkbn07) {
		this.evtkbn07 = evtkbn07;
	}

	public String getEvtkbn08() {
		return this.evtkbn08;
	}

	public void setEvtkbn08(String evtkbn08) {
		this.evtkbn08 = evtkbn08;
	}

	public String getEvtkbn09() {
		return this.evtkbn09;
	}

	public void setEvtkbn09(String evtkbn09) {
		this.evtkbn09 = evtkbn09;
	}

	public String getEvtkbn10() {
		return this.evtkbn10;
	}

	public void setEvtkbn10(String evtkbn10) {
		this.evtkbn10 = evtkbn10;
	}

	public String getEvtkbn11() {
		return this.evtkbn11;
	}

	public void setEvtkbn11(String evtkbn11) {
		this.evtkbn11 = evtkbn11;
	}

	public String getEvtkbn12() {
		return this.evtkbn12;
	}

	public void setEvtkbn12(String evtkbn12) {
		this.evtkbn12 = evtkbn12;
	}

	public String getEvtkbn13() {
		return this.evtkbn13;
	}

	public void setEvtkbn13(String evtkbn13) {
		this.evtkbn13 = evtkbn13;
	}

	public String getEvtkbn14() {
		return this.evtkbn14;
	}

	public void setEvtkbn14(String evtkbn14) {
		this.evtkbn14 = evtkbn14;
	}

	public String getEvtkbn15() {
		return this.evtkbn15;
	}

	public void setEvtkbn15(String evtkbn15) {
		this.evtkbn15 = evtkbn15;
	}

	public String getEvtkbn16() {
		return this.evtkbn16;
	}

	public void setEvtkbn16(String evtkbn16) {
		this.evtkbn16 = evtkbn16;
	}

	public String getEvtkbn17() {
		return this.evtkbn17;
	}

	public void setEvtkbn17(String evtkbn17) {
		this.evtkbn17 = evtkbn17;
	}

	public String getEvtkbn18() {
		return this.evtkbn18;
	}

	public void setEvtkbn18(String evtkbn18) {
		this.evtkbn18 = evtkbn18;
	}

	public String getEvtkbn19() {
		return this.evtkbn19;
	}

	public void setEvtkbn19(String evtkbn19) {
		this.evtkbn19 = evtkbn19;
	}

	public String getEvtkbn20() {
		return this.evtkbn20;
	}

	public void setEvtkbn20(String evtkbn20) {
		this.evtkbn20 = evtkbn20;
	}

	public String getApporgcod() {
		return this.apporgcod;
	}

	public void setApporgcod(String apporgcod) {
		this.apporgcod = apporgcod;
	}

	public String getInsnam() {
		return this.insnam;
	}

	public void setInsnam(String insnam) {
		this.insnam = insnam;
	}

	public String getInskbn() {
		return this.inskbn;
	}

	public void setInskbn(String inskbn) {
		this.inskbn = inskbn;
	}

	public String getInsmethodkbn() {
		return this.insmethodkbn;
	}

	public void setInsmethodkbn(String insmethodkbn) {
		this.insmethodkbn = insmethodkbn;
	}

	public Long getUpdeac() {
		return this.updeac;
	}

	public void setUpdeac(Long updeac) {
		this.updeac = updeac;
	}


	public String getUpdnam() {
		return this.updnam;
	}

	public void setUpdnam(String updnam) {
		this.updnam = updnam;
	}

	public String getUpdkbn() {
		return this.updkbn;
	}

	public void setUpdkbn(String updkbn) {
		this.updkbn = updkbn;
	}

	public String getUpdmethodkbn() {
		return this.updmethodkbn;
	}

	public void setUpdmethodkbn(String updmethodkbn) {
		this.updmethodkbn = updmethodkbn;
	}

	public String getAboflg() {
		return aboflg;
	}

	public void setAboflg(String aboflg) {
		this.aboflg = aboflg;
	}

	public void setUpdymdhms(Date updymdhms) {
		this.updymdhms = updymdhms;
	}

	public Date getUpdymdhms() {
		return updymdhms;
	}

	public Date getInsymdhms() {
		return insymdhms;
	}

	public void setInsymdhms(Date insymdhms) {
		this.insymdhms = insymdhms;
	}

	public String getEvtcod() {
		return evtcod;
	}

	public void setEvtcod(String evtcod) {
		this.evtcod = evtcod;
	}

	public String getTntcod() {
		return tntcod;
	}

	public void setTntcod(String tntcod) {
		this.tntcod = tntcod;
	}

	public String getGnrprpcod() {
		return gnrprpcod;
	}

	public void setGnrprpcod(String gnrprpcod) {
		this.gnrprpcod = gnrprpcod;
	}*/
    
}