package org.cloud.model;

/**
 * Lmmmtmz generated by MyEclipse Persistence Tools
 */

public class Lmmmtmz implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = -8349355521692747298L;

	private String tmeznecod;

	private String tmeznenam;

	private Long tmediff;

	private String aboflg;

	// Constructors

	/** default constructor */
	public Lmmmtmz() {
	}

	/** minimal constructor */
	public Lmmmtmz(String tmeznecod) {
		this.tmeznecod = tmeznecod;
	}

	/** full constructor */
	public Lmmmtmz(String tmeznecod, String tmeznenam, Long tmediff,
			String aboflg) {
		this.tmeznecod = tmeznecod;
		this.tmeznenam = tmeznenam;
		this.tmediff = tmediff;
		this.aboflg = aboflg;
	}

	// Property accessors

	public String getTmeznecod() {
		return this.tmeznecod;
	}

	public void setTmeznecod(String tmeznecod) {
		this.tmeznecod = tmeznecod;
	}

	public String getTmeznenam() {
		return this.tmeznenam;
	}

	public void setTmeznenam(String tmeznenam) {
		this.tmeznenam = tmeznenam;
	}

	public Long getTmediff() {
		return this.tmediff;
	}

	public void setTmediff(Long tmediff) {
		this.tmediff = tmediff;
	}

	public String getAboflg() {
		return this.aboflg;
	}

	public void setAboflg(String aboflg) {
		this.aboflg = aboflg;
	}

}