package org.cloud.model;
// default package



/**
 * Lvbttrs generated by MyEclipse Persistence Tools
 */

public class Lvbttrs  implements java.io.Serializable {


    // Fields    

     private LvbttrsId id;
     private String trssta;
     private String refnumkbn;
     private String refnum;
     private String maincarname;
     private String maincaridfname;
     private String insymdhms;
     private String insnam;
     private String inskbn;
     private String insmethodkbn;
     private Long updeac;
     private String updymdhms;
     private String updnam;
     private String updkbn;
     private String updmethodkbn;


    // Constructors

    /** default constructor */
    public Lvbttrs() {
    }

	/** minimal constructor */
    public Lvbttrs(LvbttrsId id) {
        this.id = id;
    }
    
    /** full constructor */
    public Lvbttrs(LvbttrsId id, String trssta, String refnumkbn, String refnum, String maincarname, String maincaridfname, String insymdhms, String insnam, String inskbn, String insmethodkbn, Long updeac, String updymdhms, String updnam, String updkbn, String updmethodkbn) {
        this.id = id;
        this.trssta = trssta;
        this.refnumkbn = refnumkbn;
        this.refnum = refnum;
        this.maincarname = maincarname;
        this.maincaridfname = maincaridfname;
        this.insymdhms = insymdhms;
        this.insnam = insnam;
        this.inskbn = inskbn;
        this.insmethodkbn = insmethodkbn;
        this.updeac = updeac;
        this.updymdhms = updymdhms;
        this.updnam = updnam;
        this.updkbn = updkbn;
        this.updmethodkbn = updmethodkbn;
    }

   
    // Property accessors

    public LvbttrsId getId() {
        return this.id;
    }
    
    public void setId(LvbttrsId id) {
        this.id = id;
    }

    public String getTrssta() {
        return this.trssta;
    }
    
    public void setTrssta(String trssta) {
        this.trssta = trssta;
    }

    public String getRefnumkbn() {
        return this.refnumkbn;
    }
    
    public void setRefnumkbn(String refnumkbn) {
        this.refnumkbn = refnumkbn;
    }

    public String getRefnum() {
        return this.refnum;
    }
    
    public void setRefnum(String refnum) {
        this.refnum = refnum;
    }

    public String getMaincarname() {
        return this.maincarname;
    }
    
    public void setMaincarname(String maincarname) {
        this.maincarname = maincarname;
    }

    public String getMaincaridfname() {
        return this.maincaridfname;
    }
    
    public void setMaincaridfname(String maincaridfname) {
        this.maincaridfname = maincaridfname;
    }

    public String getInsymdhms() {
        return this.insymdhms;
    }
    
    public void setInsymdhms(String insymdhms) {
        this.insymdhms = insymdhms;
    }

    public String getInsnam() {
        return this.insnam;
    }
    
    public void setInsnam(String insnam) {
        this.insnam = insnam;
    }

    public String getInskbn() {
        return this.inskbn;
    }
    
    public void setInskbn(String inskbn) {
        this.inskbn = inskbn;
    }

    public String getInsmethodkbn() {
        return this.insmethodkbn;
    }
    
    public void setInsmethodkbn(String insmethodkbn) {
        this.insmethodkbn = insmethodkbn;
    }

    public Long getUpdeac() {
        return this.updeac;
    }
    
    public void setUpdeac(Long updeac) {
        this.updeac = updeac;
    }

    public String getUpdymdhms() {
        return this.updymdhms;
    }
    
    public void setUpdymdhms(String updymdhms) {
        this.updymdhms = updymdhms;
    }

    public String getUpdnam() {
        return this.updnam;
    }
    
    public void setUpdnam(String updnam) {
        this.updnam = updnam;
    }

    public String getUpdkbn() {
        return this.updkbn;
    }
    
    public void setUpdkbn(String updkbn) {
        this.updkbn = updkbn;
    }

    public String getUpdmethodkbn() {
        return this.updmethodkbn;
    }
    
    public void setUpdmethodkbn(String updmethodkbn) {
        this.updmethodkbn = updmethodkbn;
    }
   








}