package org.cloud.model;

/**
 * Lvbtodr generated by MyEclipse Persistence Tools
 */

public class Lvbtodr implements java.io.Serializable {

	// Fields

	private LvbtodrId id;

	private String odrkbn;

	private String odrsta;

	private String refnumkbn;

	private String refnum;

	private String insymdhms;

	private String insnam;

	private String inskbn;

	private String insmethodkbn;

	private Long updeac;

	private String updymdhms;

	private String updnam;

	private String updkbn;

	private String updmethodkbn;

	// Constructors

	/** default constructor */
	public Lvbtodr() {
	}

	/** minimal constructor */
	public Lvbtodr(LvbtodrId id) {
		this.id = id;
	}

	/** full constructor */
	public Lvbtodr(LvbtodrId id, String odrkbn, String odrsta,
			String refnumkbn, String refnum, String insymdhms, String insnam,
			String inskbn, String insmethodkbn, Long updeac, String updymdhms,
			String updnam, String updkbn, String updmethodkbn) {
		this.id = id;
		this.odrkbn = odrkbn;
		this.odrsta = odrsta;
		this.refnumkbn = refnumkbn;
		this.refnum = refnum;
		this.insymdhms = insymdhms;
		this.insnam = insnam;
		this.inskbn = inskbn;
		this.insmethodkbn = insmethodkbn;
		this.updeac = updeac;
		this.updymdhms = updymdhms;
		this.updnam = updnam;
		this.updkbn = updkbn;
		this.updmethodkbn = updmethodkbn;
	}

	// Property accessors

	public LvbtodrId getId() {
		return this.id;
	}

	public void setId(LvbtodrId id) {
		this.id = id;
	}

	public String getOdrkbn() {
		return this.odrkbn;
	}

	public void setOdrkbn(String odrkbn) {
		this.odrkbn = odrkbn;
	}

	public String getOdrsta() {
		return this.odrsta;
	}

	public void setOdrsta(String odrsta) {
		this.odrsta = odrsta;
	}

	public String getRefnumkbn() {
		return this.refnumkbn;
	}

	public void setRefnumkbn(String refnumkbn) {
		this.refnumkbn = refnumkbn;
	}

	public String getRefnum() {
		return this.refnum;
	}

	public void setRefnum(String refnum) {
		this.refnum = refnum;
	}

	public String getInsymdhms() {
		return this.insymdhms;
	}

	public void setInsymdhms(String insymdhms) {
		this.insymdhms = insymdhms;
	}

	public String getInsnam() {
		return this.insnam;
	}

	public void setInsnam(String insnam) {
		this.insnam = insnam;
	}

	public String getInskbn() {
		return this.inskbn;
	}

	public void setInskbn(String inskbn) {
		this.inskbn = inskbn;
	}

	public String getInsmethodkbn() {
		return this.insmethodkbn;
	}

	public void setInsmethodkbn(String insmethodkbn) {
		this.insmethodkbn = insmethodkbn;
	}

	public Long getUpdeac() {
		return this.updeac;
	}

	public void setUpdeac(Long updeac) {
		this.updeac = updeac;
	}

	public String getUpdymdhms() {
		return this.updymdhms;
	}

	public void setUpdymdhms(String updymdhms) {
		this.updymdhms = updymdhms;
	}

	public String getUpdnam() {
		return this.updnam;
	}

	public void setUpdnam(String updnam) {
		this.updnam = updnam;
	}

	public String getUpdkbn() {
		return this.updkbn;
	}

	public void setUpdkbn(String updkbn) {
		this.updkbn = updkbn;
	}

	public String getUpdmethodkbn() {
		return this.updmethodkbn;
	}

	public void setUpdmethodkbn(String updmethodkbn) {
		this.updmethodkbn = updmethodkbn;
	}

}