package org.cloud.model;

/**
 * LvbtrutcrrId generated by MyEclipse Persistence Tools
 */

public class LvbtrutcrrId implements java.io.Serializable {

	// Fields

	private String tntcod;

	private String trsmgtnum;

	private String trscremgtnum;

	// Constructors

	/** default constructor */
	public LvbtrutcrrId() {
	}

	/** full constructor */
	public LvbtrutcrrId(String tntcod, String trsmgtnum, String trscremgtnum) {
		this.tntcod = tntcod;
		this.trsmgtnum = trsmgtnum;
		this.trscremgtnum = trscremgtnum;
	}

	// Property accessors

	public String getTntcod() {
		return this.tntcod;
	}

	public void setTntcod(String tntcod) {
		this.tntcod = tntcod;
	}

	public String getTrsmgtnum() {
		return this.trsmgtnum;
	}

	public void setTrsmgtnum(String trsmgtnum) {
		this.trsmgtnum = trsmgtnum;
	}

	public String getTrscremgtnum() {
		return this.trscremgtnum;
	}

	public void setTrscremgtnum(String trscremgtnum) {
		this.trscremgtnum = trscremgtnum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LvbtrutcrrId))
			return false;
		LvbtrutcrrId castOther = (LvbtrutcrrId) other;

		return ((this.getTntcod() == castOther.getTntcod()) || (this
				.getTntcod() != null
				&& castOther.getTntcod() != null && this.getTntcod().equals(
				castOther.getTntcod())))
				&& ((this.getTrsmgtnum() == castOther.getTrsmgtnum()) || (this
						.getTrsmgtnum() != null
						&& castOther.getTrsmgtnum() != null && this
						.getTrsmgtnum().equals(castOther.getTrsmgtnum())))
				&& ((this.getTrscremgtnum() == castOther.getTrscremgtnum()) || (this
						.getTrscremgtnum() != null
						&& castOther.getTrscremgtnum() != null && this
						.getTrscremgtnum().equals(castOther.getTrscremgtnum())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTntcod() == null ? 0 : this.getTntcod().hashCode());
		result = 37 * result
				+ (getTrsmgtnum() == null ? 0 : this.getTrsmgtnum().hashCode());
		result = 37
				* result
				+ (getTrscremgtnum() == null ? 0 : this.getTrscremgtnum()
						.hashCode());
		return result;
	}

}