package org.cloud.model;

/**
 * Lvbttrsorg generated by MyEclipse Persistence Tools
 */

public class Lvbttrsorg implements java.io.Serializable {

	// Fields

	private LvbttrsorgId id;

	private String orgkbn;

	private String orgcod;

	private String orgnam1;

	private String orgnam2;

	private String orgnam3;

	private String orgnam4;

	private String orgnam5;

	private String ctgcod;

	private String ctgnam;

	private String chgnam;

	private String telcod;

	private String faxtelcod;

	private String malnam;

	private String insymdhms;

	private String insnam;

	private String inskbn;

	private String insmethodkbn;

	private Long updeac;

	private String updymdhms;

	private String updnam;

	private String updkbn;

	private String updmethodkbn;

	// Constructors

	/** default constructor */
	public Lvbttrsorg() {
	}

	/** minimal constructor */
	public Lvbttrsorg(LvbttrsorgId id) {
		this.id = id;
	}

	/** full constructor */
	public Lvbttrsorg(LvbttrsorgId id, String orgkbn, String orgcod,
			String orgnam1, String orgnam2, String orgnam3, String orgnam4,
			String orgnam5, String ctgcod, String ctgnam, String chgnam,
			String telcod, String faxtelcod, String malnam, String insymdhms,
			String insnam, String inskbn, String insmethodkbn, Long updeac,
			String updymdhms, String updnam, String updkbn, String updmethodkbn) {
		this.id = id;
		this.orgkbn = orgkbn;
		this.orgcod = orgcod;
		this.orgnam1 = orgnam1;
		this.orgnam2 = orgnam2;
		this.orgnam3 = orgnam3;
		this.orgnam4 = orgnam4;
		this.orgnam5 = orgnam5;
		this.ctgcod = ctgcod;
		this.ctgnam = ctgnam;
		this.chgnam = chgnam;
		this.telcod = telcod;
		this.faxtelcod = faxtelcod;
		this.malnam = malnam;
		this.insymdhms = insymdhms;
		this.insnam = insnam;
		this.inskbn = inskbn;
		this.insmethodkbn = insmethodkbn;
		this.updeac = updeac;
		this.updymdhms = updymdhms;
		this.updnam = updnam;
		this.updkbn = updkbn;
		this.updmethodkbn = updmethodkbn;
	}

	// Property accessors

	public LvbttrsorgId getId() {
		return this.id;
	}

	public void setId(LvbttrsorgId id) {
		this.id = id;
	}

	public String getOrgkbn() {
		return this.orgkbn;
	}

	public void setOrgkbn(String orgkbn) {
		this.orgkbn = orgkbn;
	}

	public String getOrgcod() {
		return this.orgcod;
	}

	public void setOrgcod(String orgcod) {
		this.orgcod = orgcod;
	}

	public String getOrgnam1() {
		return this.orgnam1;
	}

	public void setOrgnam1(String orgnam1) {
		this.orgnam1 = orgnam1;
	}

	public String getOrgnam2() {
		return this.orgnam2;
	}

	public void setOrgnam2(String orgnam2) {
		this.orgnam2 = orgnam2;
	}

	public String getOrgnam3() {
		return this.orgnam3;
	}

	public void setOrgnam3(String orgnam3) {
		this.orgnam3 = orgnam3;
	}

	public String getOrgnam4() {
		return this.orgnam4;
	}

	public void setOrgnam4(String orgnam4) {
		this.orgnam4 = orgnam4;
	}

	public String getOrgnam5() {
		return this.orgnam5;
	}

	public void setOrgnam5(String orgnam5) {
		this.orgnam5 = orgnam5;
	}

	public String getCtgcod() {
		return this.ctgcod;
	}

	public void setCtgcod(String ctgcod) {
		this.ctgcod = ctgcod;
	}

	public String getCtgnam() {
		return this.ctgnam;
	}

	public void setCtgnam(String ctgnam) {
		this.ctgnam = ctgnam;
	}

	public String getChgnam() {
		return this.chgnam;
	}

	public void setChgnam(String chgnam) {
		this.chgnam = chgnam;
	}

	public String getTelcod() {
		return this.telcod;
	}

	public void setTelcod(String telcod) {
		this.telcod = telcod;
	}

	public String getFaxtelcod() {
		return this.faxtelcod;
	}

	public void setFaxtelcod(String faxtelcod) {
		this.faxtelcod = faxtelcod;
	}

	public String getMalnam() {
		return this.malnam;
	}

	public void setMalnam(String malnam) {
		this.malnam = malnam;
	}

	public String getInsymdhms() {
		return this.insymdhms;
	}

	public void setInsymdhms(String insymdhms) {
		this.insymdhms = insymdhms;
	}

	public String getInsnam() {
		return this.insnam;
	}

	public void setInsnam(String insnam) {
		this.insnam = insnam;
	}

	public String getInskbn() {
		return this.inskbn;
	}

	public void setInskbn(String inskbn) {
		this.inskbn = inskbn;
	}

	public String getInsmethodkbn() {
		return this.insmethodkbn;
	}

	public void setInsmethodkbn(String insmethodkbn) {
		this.insmethodkbn = insmethodkbn;
	}

	public Long getUpdeac() {
		return this.updeac;
	}

	public void setUpdeac(Long updeac) {
		this.updeac = updeac;
	}

	public String getUpdymdhms() {
		return this.updymdhms;
	}

	public void setUpdymdhms(String updymdhms) {
		this.updymdhms = updymdhms;
	}

	public String getUpdnam() {
		return this.updnam;
	}

	public void setUpdnam(String updnam) {
		this.updnam = updnam;
	}

	public String getUpdkbn() {
		return this.updkbn;
	}

	public void setUpdkbn(String updkbn) {
		this.updkbn = updkbn;
	}

	public String getUpdmethodkbn() {
		return this.updmethodkbn;
	}

	public void setUpdmethodkbn(String updmethodkbn) {
		this.updmethodkbn = updmethodkbn;
	}

}