package org.cloud.model;

/**
 * LvbttrsorgId generated by MyEclipse Persistence Tools
 */

public class LvbttrsorgId implements java.io.Serializable {

	// Fields

	private String tntcod;

	private String trsmgtnum;

	private String trsorgmgtnum;

	// Constructors

	/** default constructor */
	public LvbttrsorgId() {
	}

	/** full constructor */
	public LvbttrsorgId(String tntcod, String trsmgtnum, String trsorgmgtnum) {
		this.tntcod = tntcod;
		this.trsmgtnum = trsmgtnum;
		this.trsorgmgtnum = trsorgmgtnum;
	}

	// Property accessors

	public String getTntcod() {
		return this.tntcod;
	}

	public void setTntcod(String tntcod) {
		this.tntcod = tntcod;
	}

	public String getTrsmgtnum() {
		return this.trsmgtnum;
	}

	public void setTrsmgtnum(String trsmgtnum) {
		this.trsmgtnum = trsmgtnum;
	}

	public String getTrsorgmgtnum() {
		return this.trsorgmgtnum;
	}

	public void setTrsorgmgtnum(String trsorgmgtnum) {
		this.trsorgmgtnum = trsorgmgtnum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LvbttrsorgId))
			return false;
		LvbttrsorgId castOther = (LvbttrsorgId) other;

		return ((this.getTntcod() == castOther.getTntcod()) || (this
				.getTntcod() != null
				&& castOther.getTntcod() != null && this.getTntcod().equals(
				castOther.getTntcod())))
				&& ((this.getTrsmgtnum() == castOther.getTrsmgtnum()) || (this
						.getTrsmgtnum() != null
						&& castOther.getTrsmgtnum() != null && this
						.getTrsmgtnum().equals(castOther.getTrsmgtnum())))
				&& ((this.getTrsorgmgtnum() == castOther.getTrsorgmgtnum()) || (this
						.getTrsorgmgtnum() != null
						&& castOther.getTrsorgmgtnum() != null && this
						.getTrsorgmgtnum().equals(castOther.getTrsorgmgtnum())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTntcod() == null ? 0 : this.getTntcod().hashCode());
		result = 37 * result
				+ (getTrsmgtnum() == null ? 0 : this.getTrsmgtnum().hashCode());
		result = 37
				* result
				+ (getTrsorgmgtnum() == null ? 0 : this.getTrsorgmgtnum()
						.hashCode());
		return result;
	}

}