package org.cloud.model;

import java.util.Date;

/**
 * Lvbtrutcrr generated by MyEclipse Persistence Tools
 */

public class Lvbtrutcrr implements java.io.Serializable {

	// Fields

	private LvbtrutcrrId id;

	private String estreskbn;

	private String refnum;

	private Long rutodrnum;

	private String evtcod;

	private String evtnam;

	private String evtkbn;

	private String evtmrgcod;

	private String evtmrgnam;

	private String altkbn;

	private String atnfil;

	private String atncrpkbn;

	private String refgrpcod;

	private String updgrpcod;

	private String plccod;

	private String plcnam;

	private String orgcod;

	private String orgnam1;

	private String orgnam2;

	private String orgnam3;

	private String orgnam4;

	private String orgnam5;

	private Date inisdlymd;

	private Date inisdlhms;

	private Date nowsdlymd;

	private Date nowsdlhms;

	private Date resymd;

	private String reshms;

	private String rmktxtfil;

	private String insymdhms;

	private String insnam;

	private String inskbn;

	private String insmethodkbn;

	private Long updeac;

	private String updymdhms;

	private String updnam;

	private String updkbn;

	private String updmethodkbn;

	// Constructors
	/** default constructor */
	public Lvbtrutcrr() {
	}
	/** minimal constructor */
	public Lvbtrutcrr(LvbtrutcrrId id) {
		this.id = id;
	}

	/** full constructor */
	public Lvbtrutcrr(LvbtrutcrrId id, String estreskbn, String refnum,
			Long rutodrnum, String evtcod, String evtnam, String evtkbn,
			String evtmrgcod, String evtmrgnam, String altkbn, String atnfil,
			String atncrpkbn, String refgrpcod, String updgrpcod,
			String plccod, String plcnam, String orgcod, String orgnam1,
			String orgnam2, String orgnam3, String orgnam4, String orgnam5,
			Date inisdlymd, Date inisdlhms, Date nowsdlymd, Date nowsdlhms,
			Date resymd, String reshms, String rmktxtfil, String insymdhms,
			String insnam, String inskbn, String insmethodkbn, Long updeac,
			String updymdhms, String updnam, String updkbn, String updmethodkbn) {
		this.id = id;
		this.estreskbn = estreskbn;
		this.refnum = refnum;
		this.rutodrnum = rutodrnum;
		this.evtcod = evtcod;
		this.evtnam = evtnam;
		this.evtkbn = evtkbn;
		this.evtmrgcod = evtmrgcod;
		this.evtmrgnam = evtmrgnam;
		this.altkbn = altkbn;
		this.atnfil = atnfil;
		this.atncrpkbn = atncrpkbn;
		this.refgrpcod = refgrpcod;
		this.updgrpcod = updgrpcod;
		this.plccod = plccod;
		this.plcnam = plcnam;
		this.orgcod = orgcod;
		this.orgnam1 = orgnam1;
		this.orgnam2 = orgnam2;
		this.orgnam3 = orgnam3;
		this.orgnam4 = orgnam4;
		this.orgnam5 = orgnam5;
		this.inisdlymd = inisdlymd;
		this.inisdlhms = inisdlhms;
		this.nowsdlymd = nowsdlymd;
		this.nowsdlhms = nowsdlhms;
		this.resymd = resymd;
		this.reshms = reshms;
		this.rmktxtfil = rmktxtfil;
		this.insymdhms = insymdhms;
		this.insnam = insnam;
		this.inskbn = inskbn;
		this.insmethodkbn = insmethodkbn;
		this.updeac = updeac;
		this.updymdhms = updymdhms;
		this.updnam = updnam;
		this.updkbn = updkbn;
		this.updmethodkbn = updmethodkbn;
	}

	// Property accessors

	public LvbtrutcrrId getId() {
		return this.id;
	}

	public void setId(LvbtrutcrrId id) {
		this.id = id;
	}

	public String getEstreskbn() {
		return this.estreskbn;
	}

	public void setEstreskbn(String estreskbn) {
		this.estreskbn = estreskbn;
	}

	public String getRefnum() {
		return this.refnum;
	}

	public void setRefnum(String refnum) {
		this.refnum = refnum;
	}

	public Long getRutodrnum() {
		return this.rutodrnum;
	}

	public void setRutodrnum(Long rutodrnum) {
		this.rutodrnum = rutodrnum;
	}

	public String getEvtcod() {
		return this.evtcod;
	}

	public void setEvtcod(String evtcod) {
		this.evtcod = evtcod;
	}

	public String getEvtnam() {
		return this.evtnam;
	}

	public void setEvtnam(String evtnam) {
		this.evtnam = evtnam;
	}

	public String getEvtkbn() {
		return this.evtkbn;
	}

	public void setEvtkbn(String evtkbn) {
		this.evtkbn = evtkbn;
	}

	public String getEvtmrgcod() {
		return this.evtmrgcod;
	}

	public void setEvtmrgcod(String evtmrgcod) {
		this.evtmrgcod = evtmrgcod;
	}

	public String getEvtmrgnam() {
		return this.evtmrgnam;
	}

	public void setEvtmrgnam(String evtmrgnam) {
		this.evtmrgnam = evtmrgnam;
	}

	public String getAltkbn() {
		return this.altkbn;
	}

	public void setAltkbn(String altkbn) {
		this.altkbn = altkbn;
	}

	public String getAtnfil() {
		return this.atnfil;
	}

	public void setAtnfil(String atnfil) {
		this.atnfil = atnfil;
	}

	public String getAtncrpkbn() {
		return this.atncrpkbn;
	}

	public void setAtncrpkbn(String atncrpkbn) {
		this.atncrpkbn = atncrpkbn;
	}

	public String getRefgrpcod() {
		return this.refgrpcod;
	}

	public void setRefgrpcod(String refgrpcod) {
		this.refgrpcod = refgrpcod;
	}

	public String getUpdgrpcod() {
		return this.updgrpcod;
	}

	public void setUpdgrpcod(String updgrpcod) {
		this.updgrpcod = updgrpcod;
	}

	public String getPlccod() {
		return this.plccod;
	}

	public void setPlccod(String plccod) {
		this.plccod = plccod;
	}

	public String getPlcnam() {
		return this.plcnam;
	}

	public void setPlcnam(String plcnam) {
		this.plcnam = plcnam;
	}

	public String getOrgcod() {
		return this.orgcod;
	}

	public void setOrgcod(String orgcod) {
		this.orgcod = orgcod;
	}

	public String getOrgnam1() {
		return this.orgnam1;
	}

	public void setOrgnam1(String orgnam1) {
		this.orgnam1 = orgnam1;
	}

	public String getOrgnam2() {
		return this.orgnam2;
	}

	public void setOrgnam2(String orgnam2) {
		this.orgnam2 = orgnam2;
	}

	public String getOrgnam3() {
		return this.orgnam3;
	}

	public void setOrgnam3(String orgnam3) {
		this.orgnam3 = orgnam3;
	}

	public String getOrgnam4() {
		return this.orgnam4;
	}

	public void setOrgnam4(String orgnam4) {
		this.orgnam4 = orgnam4;
	}

	public String getOrgnam5() {
		return this.orgnam5;
	}

	public void setOrgnam5(String orgnam5) {
		this.orgnam5 = orgnam5;
	}

	public Date getInisdlymd() {
		return this.inisdlymd;
	}

	public void setInisdlymd(Date inisdlymd) {
		this.inisdlymd = inisdlymd;
	}

	public Date getInisdlhms() {
		return this.inisdlhms;
	}

	public void setInisdlhms(Date inisdlhms) {
		this.inisdlhms = inisdlhms;
	}

	public Date getNowsdlymd() {
		return this.nowsdlymd;
	}

	public void setNowsdlymd(Date nowsdlymd) {
		this.nowsdlymd = nowsdlymd;
	}

	public Date getNowsdlhms() {
		return this.nowsdlhms;
	}

	public void setNowsdlhms(Date nowsdlhms) {
		this.nowsdlhms = nowsdlhms;
	}

	public Date getResymd() {
		return this.resymd;
	}

	public void setResymd(Date resymd) {
		this.resymd = resymd;
	}

	public String getReshms() {
		return this.reshms;
	}

	public void setReshms(String reshms) {
		this.reshms = reshms;
	}

	public String getRmktxtfil() {
		return this.rmktxtfil;
	}

	public void setRmktxtfil(String rmktxtfil) {
		this.rmktxtfil = rmktxtfil;
	}

	public String getInsymdhms() {
		return this.insymdhms;
	}

	public void setInsymdhms(String insymdhms) {
		this.insymdhms = insymdhms;
	}

	public String getInsnam() {
		return this.insnam;
	}

	public void setInsnam(String insnam) {
		this.insnam = insnam;
	}

	public String getInskbn() {
		return this.inskbn;
	}

	public void setInskbn(String inskbn) {
		this.inskbn = inskbn;
	}

	public String getInsmethodkbn() {
		return this.insmethodkbn;
	}

	public void setInsmethodkbn(String insmethodkbn) {
		this.insmethodkbn = insmethodkbn;
	}

	public Long getUpdeac() {
		return this.updeac;
	}

	public void setUpdeac(Long updeac) {
		this.updeac = updeac;
	}

	public String getUpdymdhms() {
		return this.updymdhms;
	}

	public void setUpdymdhms(String updymdhms) {
		this.updymdhms = updymdhms;
	}

	public String getUpdnam() {
		return this.updnam;
	}

	public void setUpdnam(String updnam) {
		this.updnam = updnam;
	}

	public String getUpdkbn() {
		return this.updkbn;
	}

	public void setUpdkbn(String updkbn) {
		this.updkbn = updkbn;
	}

	public String getUpdmethodkbn() {
		return this.updmethodkbn;
	}

	public void setUpdmethodkbn(String updmethodkbn) {
		this.updmethodkbn = updmethodkbn;
	}

}