package org.cloud.model;

/**
 * LvbtodrplcId generated by MyEclipse Persistence Tools
 */

public class LvbtodrplcId implements java.io.Serializable {

	// Fields

	private String tntcod;

	private String odrmgtnum;

	private String odrplcnum;

	// Constructors

	/** default constructor */
	public LvbtodrplcId() {
	}

	/** full constructor */
	public LvbtodrplcId(String tntcod, String odrmgtnum, String odrplcnum) {
		this.tntcod = tntcod;
		this.odrmgtnum = odrmgtnum;
		this.odrplcnum = odrplcnum;
	}

	// Property accessors

	public String getTntcod() {
		return this.tntcod;
	}

	public void setTntcod(String tntcod) {
		this.tntcod = tntcod;
	}

	public String getOdrmgtnum() {
		return this.odrmgtnum;
	}

	public void setOdrmgtnum(String odrmgtnum) {
		this.odrmgtnum = odrmgtnum;
	}

	public String getOdrplcnum() {
		return this.odrplcnum;
	}

	public void setOdrplcnum(String odrplcnum) {
		this.odrplcnum = odrplcnum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LvbtodrplcId))
			return false;
		LvbtodrplcId castOther = (LvbtodrplcId) other;

		return ((this.getTntcod() == castOther.getTntcod()) || (this
				.getTntcod() != null
				&& castOther.getTntcod() != null && this.getTntcod().equals(
				castOther.getTntcod())))
				&& ((this.getOdrmgtnum() == castOther.getOdrmgtnum()) || (this
						.getOdrmgtnum() != null
						&& castOther.getOdrmgtnum() != null && this
						.getOdrmgtnum().equals(castOther.getOdrmgtnum())))
				&& ((this.getOdrplcnum() == castOther.getOdrplcnum()) || (this
						.getOdrplcnum() != null
						&& castOther.getOdrplcnum() != null && this
						.getOdrplcnum().equals(castOther.getOdrplcnum())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTntcod() == null ? 0 : this.getTntcod().hashCode());
		result = 37 * result
				+ (getOdrmgtnum() == null ? 0 : this.getOdrmgtnum().hashCode());
		result = 37 * result
				+ (getOdrplcnum() == null ? 0 : this.getOdrplcnum().hashCode());
		return result;
	}

}