package org.cloud.model;

/**
 * LmmmevtId generated by MyEclipse Persistence Tools
 */

public class LmmmevtId implements java.io.Serializable {

	// Fields

	private String tntcod;

	private String evtcod;

	// Constructors

	/** default constructor */
	public LmmmevtId() {
	}

	/** full constructor */
	public LmmmevtId(String tntcod, String evtcod) {
		this.tntcod = tntcod;
		this.evtcod = evtcod;
	}

	// Property accessors

	public String getTntcod() {
		return this.tntcod;
	}

	public void setTntcod(String tntcod) {
		this.tntcod = tntcod;
	}

	public String getEvtcod() {
		return this.evtcod;
	}

	public void setEvtcod(String evtcod) {
		this.evtcod = evtcod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LmmmevtId))
			return false;
		LmmmevtId castOther = (LmmmevtId) other;

		return ((this.getTntcod() == castOther.getTntcod()) || (this
				.getTntcod() != null
				&& castOther.getTntcod() != null && this.getTntcod().equals(
				castOther.getTntcod())))
				&& ((this.getEvtcod() == castOther.getEvtcod()) || (this
						.getEvtcod() != null
						&& castOther.getEvtcod() != null && this.getEvtcod()
						.equals(castOther.getEvtcod())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTntcod() == null ? 0 : this.getTntcod().hashCode());
		result = 37 * result
				+ (getEvtcod() == null ? 0 : this.getEvtcod().hashCode());
		return result;
	}

}