package org.cloud.model;

/**
 * Lvbtodrplc generated by MyEclipse Persistence Tools
 */

public class Lvbtodrplc implements java.io.Serializable {

	// Fields

	private LvbtodrplcId id;

	private String plckbn;

	private String plccod;

	private String plcnam;

	private String adrnam1;

	private String adrnam2;

	private String adrnam3;

	private String adrnam4;

	private String zipcod;

	private String ctrcod;

	private String tmeznecod;

	private String insymdhms;

	private String insnam;

	private String inskbn;

	private String insmethodkbn;

	private Long updeac;

	private String updymdhms;

	private String updnam;

	private String updkbn;

	private String updmethodkbn;

	// Constructors

	/** default constructor */
	public Lvbtodrplc() {
	}

	/** minimal constructor */
	public Lvbtodrplc(LvbtodrplcId id) {
		this.id = id;
	}

	/** full constructor */
	public Lvbtodrplc(LvbtodrplcId id, String plckbn, String plccod,
			String plcnam, String adrnam1, String adrnam2, String adrnam3,
			String adrnam4, String zipcod, String ctrcod, String tmeznecod,
			String insymdhms, String insnam, String inskbn,
			String insmethodkbn, Long updeac, String updymdhms, String updnam,
			String updkbn, String updmethodkbn) {
		this.id = id;
		this.plckbn = plckbn;
		this.plccod = plccod;
		this.plcnam = plcnam;
		this.adrnam1 = adrnam1;
		this.adrnam2 = adrnam2;
		this.adrnam3 = adrnam3;
		this.adrnam4 = adrnam4;
		this.zipcod = zipcod;
		this.ctrcod = ctrcod;
		this.tmeznecod = tmeznecod;
		this.insymdhms = insymdhms;
		this.insnam = insnam;
		this.inskbn = inskbn;
		this.insmethodkbn = insmethodkbn;
		this.updeac = updeac;
		this.updymdhms = updymdhms;
		this.updnam = updnam;
		this.updkbn = updkbn;
		this.updmethodkbn = updmethodkbn;
	}

	// Property accessors

	public LvbtodrplcId getId() {
		return this.id;
	}

	public void setId(LvbtodrplcId id) {
		this.id = id;
	}

	public String getPlckbn() {
		return this.plckbn;
	}

	public void setPlckbn(String plckbn) {
		this.plckbn = plckbn;
	}

	public String getPlccod() {
		return this.plccod;
	}

	public void setPlccod(String plccod) {
		this.plccod = plccod;
	}

	public String getPlcnam() {
		return this.plcnam;
	}

	public void setPlcnam(String plcnam) {
		this.plcnam = plcnam;
	}

	public String getAdrnam1() {
		return this.adrnam1;
	}

	public void setAdrnam1(String adrnam1) {
		this.adrnam1 = adrnam1;
	}

	public String getAdrnam2() {
		return this.adrnam2;
	}

	public void setAdrnam2(String adrnam2) {
		this.adrnam2 = adrnam2;
	}

	public String getAdrnam3() {
		return this.adrnam3;
	}

	public void setAdrnam3(String adrnam3) {
		this.adrnam3 = adrnam3;
	}

	public String getAdrnam4() {
		return this.adrnam4;
	}

	public void setAdrnam4(String adrnam4) {
		this.adrnam4 = adrnam4;
	}

	public String getZipcod() {
		return this.zipcod;
	}

	public void setZipcod(String zipcod) {
		this.zipcod = zipcod;
	}

	public String getCtrcod() {
		return this.ctrcod;
	}

	public void setCtrcod(String ctrcod) {
		this.ctrcod = ctrcod;
	}

	public String getTmeznecod() {
		return this.tmeznecod;
	}

	public void setTmeznecod(String tmeznecod) {
		this.tmeznecod = tmeznecod;
	}

	public String getInsymdhms() {
		return this.insymdhms;
	}

	public void setInsymdhms(String insymdhms) {
		this.insymdhms = insymdhms;
	}

	public String getInsnam() {
		return this.insnam;
	}

	public void setInsnam(String insnam) {
		this.insnam = insnam;
	}

	public String getInskbn() {
		return this.inskbn;
	}

	public void setInskbn(String inskbn) {
		this.inskbn = inskbn;
	}

	public String getInsmethodkbn() {
		return this.insmethodkbn;
	}

	public void setInsmethodkbn(String insmethodkbn) {
		this.insmethodkbn = insmethodkbn;
	}

	public Long getUpdeac() {
		return this.updeac;
	}

	public void setUpdeac(Long updeac) {
		this.updeac = updeac;
	}

	public String getUpdymdhms() {
		return this.updymdhms;
	}

	public void setUpdymdhms(String updymdhms) {
		this.updymdhms = updymdhms;
	}

	public String getUpdnam() {
		return this.updnam;
	}

	public void setUpdnam(String updnam) {
		this.updnam = updnam;
	}

	public String getUpdkbn() {
		return this.updkbn;
	}

	public void setUpdkbn(String updkbn) {
		this.updkbn = updkbn;
	}

	public String getUpdmethodkbn() {
		return this.updmethodkbn;
	}

	public void setUpdmethodkbn(String updmethodkbn) {
		this.updmethodkbn = updmethodkbn;
	}

}