package org.cloud.model;

import java.util.Date;

/**
 * LmmmorgId generated by MyEclipse Persistence Tools
 */

public class LmmmorgId implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String tntcod;

	private String orgcod;

	private Date appstaymdhms;

	// Constructors

	/** default constructor */
	public LmmmorgId() {
	}

	/** full constructor */
	public LmmmorgId(String tntcod, String orgcod, Date appstaymdhms) {
		this.tntcod = tntcod;
		this.orgcod = orgcod;
		this.appstaymdhms = appstaymdhms;
	}

	// Property accessors

	public String getTntcod() {
		return this.tntcod;
	}

	public void setTntcod(String tntcod) {
		this.tntcod = tntcod;
	}

	public String getOrgcod() {
		return this.orgcod;
	}

	public void setOrgcod(String orgcod) {
		this.orgcod = orgcod;
	}

	public Date getAppstaymdhms() {
		return this.appstaymdhms;
	}

	public void setAppstaymdhms(Date appstaymdhms) {
		this.appstaymdhms = appstaymdhms;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LmmmorgId))
			return false;
		LmmmorgId castOther = (LmmmorgId) other;

		return ((this.getTntcod() == castOther.getTntcod()) || (this
				.getTntcod() != null
				&& castOther.getTntcod() != null && this.getTntcod().equals(
				castOther.getTntcod())))
				&& ((this.getOrgcod() == castOther.getOrgcod()) || (this
						.getOrgcod() != null
						&& castOther.getOrgcod() != null && this.getOrgcod()
						.equals(castOther.getOrgcod())))
				&& ((this.getAppstaymdhms() == castOther.getAppstaymdhms()) || (this
						.getAppstaymdhms() != null
						&& castOther.getAppstaymdhms() != null && this
						.getAppstaymdhms().equals(castOther.getAppstaymdhms())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTntcod() == null ? 0 : this.getTntcod().hashCode());
		result = 37 * result
				+ (getOrgcod() == null ? 0 : this.getOrgcod().hashCode());
		result = 37
				* result
				+ (getAppstaymdhms() == null ? 0 : this.getAppstaymdhms()
						.hashCode());
		return result;
	}

}