package org.cloud.model;

/**
 * LvbtodrorgId generated by MyEclipse Persistence Tools
 */

public class LvbtodrorgId implements java.io.Serializable {

	// Fields

	private String tntcod;

	private String odrmgtnum;

	private String odrorgmgtnum;

	// Constructors

	/** default constructor */
	public LvbtodrorgId() {
	}

	/** full constructor */
	public LvbtodrorgId(String tntcod, String odrmgtnum, String odrorgmgtnum) {
		this.tntcod = tntcod;
		this.odrmgtnum = odrmgtnum;
		this.odrorgmgtnum = odrorgmgtnum;
	}

	// Property accessors

	public String getTntcod() {
		return this.tntcod;
	}

	public void setTntcod(String tntcod) {
		this.tntcod = tntcod;
	}

	public String getOdrmgtnum() {
		return this.odrmgtnum;
	}

	public void setOdrmgtnum(String odrmgtnum) {
		this.odrmgtnum = odrmgtnum;
	}

	public String getOdrorgmgtnum() {
		return this.odrorgmgtnum;
	}

	public void setOdrorgmgtnum(String odrorgmgtnum) {
		this.odrorgmgtnum = odrorgmgtnum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LvbtodrorgId))
			return false;
		LvbtodrorgId castOther = (LvbtodrorgId) other;

		return ((this.getTntcod() == castOther.getTntcod()) || (this
				.getTntcod() != null
				&& castOther.getTntcod() != null && this.getTntcod().equals(
				castOther.getTntcod())))
				&& ((this.getOdrmgtnum() == castOther.getOdrmgtnum()) || (this
						.getOdrmgtnum() != null
						&& castOther.getOdrmgtnum() != null && this
						.getOdrmgtnum().equals(castOther.getOdrmgtnum())))
				&& ((this.getOdrorgmgtnum() == castOther.getOdrorgmgtnum()) || (this
						.getOdrorgmgtnum() != null
						&& castOther.getOdrorgmgtnum() != null && this
						.getOdrorgmgtnum().equals(castOther.getOdrorgmgtnum())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTntcod() == null ? 0 : this.getTntcod().hashCode());
		result = 37 * result
				+ (getOdrmgtnum() == null ? 0 : this.getOdrmgtnum().hashCode());
		result = 37
				* result
				+ (getOdrorgmgtnum() == null ? 0 : this.getOdrorgmgtnum()
						.hashCode());
		return result;
	}

}