package org.cloud.model;

/**
 * Lmmmusr generated by MyEclipse Persistence Tools
 */

public class Lmmmusr implements java.io.Serializable {

	// Fields

	private LmmmusrId id;

	private String aboflg;

	private String usrnam;

	private String belorgcod;

	private String disprol;

	private String uselancod;

	private String tmeznecod;

	private String ctrcod;

	private String usrtypkbn;

	private String apporgcod;

	private String appstaymdhms;

	private String appendymdhms;

	private String insymdhms;

	private String insnam;

	private String inskbn;

	private String insmethodkbn;

	private Long updeac;

	private String updymdhms;

	private String updnam;

	private String updkbn;

	private String updmethodkbn;

	// Constructors

	/** default constructor */
	public Lmmmusr() {
	}

	/** minimal constructor */
	public Lmmmusr(LmmmusrId id) {
		this.id = id;
	}

	/** full constructor */
	public Lmmmusr(LmmmusrId id, String aboflg, String usrnam,
			String belorgcod, String disprol, String uselancod,
			String tmeznecod, String ctrcod, String usrtypkbn,
			String apporgcod, String appstaymdhms, String appendymdhms,
			String insymdhms, String insnam, String inskbn,
			String insmethodkbn, Long updeac, String updymdhms, String updnam,
			String updkbn, String updmethodkbn) {
		this.id = id;
		this.aboflg = aboflg;
		this.usrnam = usrnam;
		this.belorgcod = belorgcod;
		this.disprol = disprol;
		this.uselancod = uselancod;
		this.tmeznecod = tmeznecod;
		this.ctrcod = ctrcod;
		this.usrtypkbn = usrtypkbn;
		this.apporgcod = apporgcod;
		this.appstaymdhms = appstaymdhms;
		this.appendymdhms = appendymdhms;
		this.insymdhms = insymdhms;
		this.insnam = insnam;
		this.inskbn = inskbn;
		this.insmethodkbn = insmethodkbn;
		this.updeac = updeac;
		this.updymdhms = updymdhms;
		this.updnam = updnam;
		this.updkbn = updkbn;
		this.updmethodkbn = updmethodkbn;
	}

	// Property accessors

	public LmmmusrId getId() {
		return this.id;
	}

	public void setId(LmmmusrId id) {
		this.id = id;
	}

	public String getAboflg() {
		return this.aboflg;
	}

	public void setAboflg(String aboflg) {
		this.aboflg = aboflg;
	}

	public String getUsrnam() {
		return this.usrnam;
	}

	public void setUsrnam(String usrnam) {
		this.usrnam = usrnam;
	}

	public String getBelorgcod() {
		return this.belorgcod;
	}

	public void setBelorgcod(String belorgcod) {
		this.belorgcod = belorgcod;
	}

	public String getDisprol() {
		return this.disprol;
	}

	public void setDisprol(String disprol) {
		this.disprol = disprol;
	}

	public String getUselancod() {
		return this.uselancod;
	}

	public void setUselancod(String uselancod) {
		this.uselancod = uselancod;
	}

	public String getTmeznecod() {
		return this.tmeznecod;
	}

	public void setTmeznecod(String tmeznecod) {
		this.tmeznecod = tmeznecod;
	}

	public String getCtrcod() {
		return this.ctrcod;
	}

	public void setCtrcod(String ctrcod) {
		this.ctrcod = ctrcod;
	}

	public String getUsrtypkbn() {
		return this.usrtypkbn;
	}

	public void setUsrtypkbn(String usrtypkbn) {
		this.usrtypkbn = usrtypkbn;
	}

	public String getApporgcod() {
		return this.apporgcod;
	}

	public void setApporgcod(String apporgcod) {
		this.apporgcod = apporgcod;
	}

	public String getAppstaymdhms() {
		return this.appstaymdhms;
	}

	public void setAppstaymdhms(String appstaymdhms) {
		this.appstaymdhms = appstaymdhms;
	}

	public String getAppendymdhms() {
		return this.appendymdhms;
	}

	public void setAppendymdhms(String appendymdhms) {
		this.appendymdhms = appendymdhms;
	}

	public String getInsymdhms() {
		return this.insymdhms;
	}

	public void setInsymdhms(String insymdhms) {
		this.insymdhms = insymdhms;
	}

	public String getInsnam() {
		return this.insnam;
	}

	public void setInsnam(String insnam) {
		this.insnam = insnam;
	}

	public String getInskbn() {
		return this.inskbn;
	}

	public void setInskbn(String inskbn) {
		this.inskbn = inskbn;
	}

	public String getInsmethodkbn() {
		return this.insmethodkbn;
	}

	public void setInsmethodkbn(String insmethodkbn) {
		this.insmethodkbn = insmethodkbn;
	}

	public Long getUpdeac() {
		return this.updeac;
	}

	public void setUpdeac(Long updeac) {
		this.updeac = updeac;
	}

	public String getUpdymdhms() {
		return this.updymdhms;
	}

	public void setUpdymdhms(String updymdhms) {
		this.updymdhms = updymdhms;
	}

	public String getUpdnam() {
		return this.updnam;
	}

	public void setUpdnam(String updnam) {
		this.updnam = updnam;
	}

	public String getUpdkbn() {
		return this.updkbn;
	}

	public void setUpdkbn(String updkbn) {
		this.updkbn = updkbn;
	}

	public String getUpdmethodkbn() {
		return this.updmethodkbn;
	}

	public void setUpdmethodkbn(String updmethodkbn) {
		this.updmethodkbn = updmethodkbn;
	}

}